ToucanToco/toucan-connectors

- README.md
- doc/dataiku.md
- setup.py
- tests/dataiku/test_dataiku_connector.py
- toucan_connectors/__init__.py
- toucan_connectors/dataiku/dataiku_connector.py
This is a basic connector for [Dataiku](https://www.dataiku.com/) using their [DSS API](https://doc.dataiku.com/dss/2.0/api/index.html).
> Dataiku connector

- doc/adobe.md
- setup.py
- tests/adobe/test_adobe_connector.py
- tests/dataiku/test_dataiku_connector.py
- toucan_connectors/__init__.py
- toucan_connectors/adobe/adobe_connector.py
Connector using Adobe Analytics' REST API v1.4. It provides a high-level interfaces for reporting queries (including Data Warehouse requests).
> Feature :: adobe analytics

- doc/generate.py
- tests/adobe_analytics/test_adobe_analytics_connector.py
- toucan_connectors/adobe_analytics/adobe_analytics_connector.py
Added default value dimensions for the "dimensions" parameter of the AdobeAnalyticsDataSource
> Hotfix :: Added default value for dimensions

- .circleci/config.yml
- doc/mysql.md
- setup.cfg
- setup.py
- tests/conftest.py
- tests/google_analytics/test_google_analytics.py
- tests/mongo/test_mongo.py
- tests/mssql/test_mssql.py
- tests/mysql/test_mysql.py
- tests/oracle_sql/test_oracle_sql.py
- tests/postgres/test_postgres.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mysql/mysql_connector.py
Nothing special except the CI works again
⚠️ `follow_relations` is now set to False by default ⚠️ 
It means by default the SQL connector will just execute the query without doing a lot of things like merging with whatever...
If no bug is reported we should be able to remove all this shitty code
> Migration to Circle 2.0

- tests/postgres/test_postgres.py
- toucan_connectors/postgres/postgresql_connector.py
> Postgres :: Add params to data source

- setup.py
- toucan_connectors/google_analytics/google_analytics_connector.py
Add segmentId for Google Analytics
> Feature :: Google Analytics segmentId

- doc/mongo.md
Othrewise we cannot embed this readme in ToucanToco doc : https://github.com/ToucanToco/doc/pull/354
> Remove 'eval_rst' block

- doc/connectors.md
- doc/magento.md
- setup.py
- tests/magento/test_magento.py
- toucan_connectors/__init__.py
- toucan_connectors/magento/magento_connector.py
Basic support for now, may need to grow up : undelying lib seems fragile and not very usefull, could be tested with a container also.
> Magento :: add connector

- doc/http_api.md
- doc/odata.md
- setup.py
- tests/http_api/test_http_api.py
- tests/odata/test_odata.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/odata/odata_connector.py
> OData :: improvements (better names for params, more auth)

- doc/generate.py
- setup.py
- tests/docker-compose.yml
- tests/oracle_sql/test_oracle_sql.py
- toucan_connectors/toucan_connector.py
Needed for https://github.com/ToucanToco/laputa/pull/2409
> Allow validation field

- .circleci/config.yml
- setup.py
- toucan_connectors/http_api/http_api_connector.py
Add possibility for parameter `data` to be a dict
>  Http api : authorize dict for parameter data

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Some improvements for mongo connector:
- Fix handle_missing_paramas for value not dict/list/str
- Raise error if collection doesn't exist
> Feature :: update mongo connector

- setup.py
- tests/mongo/test_mongo.py
- tests/test_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/toucan_connector.py
Add methods 
* `get_df_and_count` : retrieves a part of the data and the total count
* `explain`: returns metrics about the query
> Feature :: add methods get_df_and_count + explain

- README.md
- templates/connector.py.m4
- tests/mongo/test_mongo.py
- tests/mysql/test_mysql.py
- tests/test_connector.py
- toucan_connectors/__init__.py
- toucan_connectors/adobe_analytics/adobe_analytics_connector.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/dataiku/dataiku_connector.py
- toucan_connectors/elasticsearch/elasticsearch_connector.py
- toucan_connectors/facebook_insights/facebook_insights_connector.py
- toucan_connectors/google_analytics/google_analytics_connector.py
- toucan_connectors/google_big_query/google_big_query_connector.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/google_my_business/google_my_business_connector.py
- toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
- toucan_connectors/hive/hive_connector.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/micro_strategy/micro_strategy_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/odata/odata_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/sap_hana/sap_hana_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/toucan_connector.py
- toucan_connectors/toucan_toco/toucan_toco_connector.py
- toucan_connectors/trello/trello_connector.py
Add `get_status` and a constant for all existing connectors
(required for connector's interface)
https://github.com/ToucanToco/laputa/pull/2544
> Get status and all connectors

- README.md
- templates/connector.py.m4
New connectors should only care about implementing `_retrieve_data`
> [template] follow recent get_df vs. _retrieve_data API changes

- setup.py
Make jq required : allow us to have MongoConnector availabled on laputa by default
> Tech :: Make jq required

- doc/connectors.md
- doc/connectors/wootric.md
- requirements-testing.txt
- setup.py
- tests/wootric/test_wootric.py
- toucan_connectors/__init__.py
- toucan_connectors/wootric/wootric_connector.py
cf. https://docs.wootric.com/api and connector documentation.
> wootric :: new connector

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Or else it returns 0 documents.
> mongo connector :: fix get_df_and_count when the query uses $group aggregation

- tests/elasticsearch/test_elasticsearch.py
- toucan_connectors/elasticsearch/elasticsearch_connector.py
For Elasticsearch, read aggregations in response if 'aggs' in body
> Elasticsearch :: Read aggregations in response

- doc/connectors/azure_mssql.md
- doc/connectors/google_cloud_mysql.md
- doc/connectors/hive.md
- doc/connectors/mongo.md
- doc/connectors/mssql.md
- doc/connectors/mysql.md
- doc/connectors/postgres.md
- doc/generate.py
- setup.py
- tests/azure_mssql/test_azure_mssql.py
- tests/google_cloud_mysql/test_google_cloud_mysql.py
- tests/mongo/test_mongo.py
- tests/mssql/test_mssql.py
- tests/mysql/test_mysql.py
- tests/postgres/test_postgres.py
- tests/test_connector.py
- tests/test_datasource.py
- toucan_connectors/__init__.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/hive/hive_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/toucan_connector.py
⚠️ If approved, this PR will need a version bump. On laputa, we will need a dedicated PR with the version bump of toucan-connectors and the migration for all the modified connectors
> Feature :: get form

- .circleci/config.yml
see https://askubuntu.com/a/865569
> [ci] Change PPA to download python 3.6 on ubuntu 14.04

- doc/connectors.md
- doc/connectors/ROK.md
- setup.py
- tests/http_api/test_http_api.py
- tests/rok/test_rok.py
- toucan_connectors/__init__.py
- toucan_connectors/common.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/rok/rok_connector.py
New connector towards ROK Solution (cf. https://www.rok-solution.fr/). The underlying API is GraphQL, but with a "custom" auth mechanism so we make a specific connector for the moment.
> ROK :: new connector

- setup.py
> Bump version to 0.32.0

- requirements-testing.txt
- setup.py
- also froze version of pytest-asyncio to that of what's used in laputa
> Bumped version of Toucan Connectors

- tests/aircall/mock_results.py
- tests/aircall/test_helpers.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/aircall/helpers.py
A potential solution for a blocked AirCall template issue when user is None.
Should resolve [Trello card](https://trello.com/c/i01HjLg4/447-5-etqc-je-peux-cr%C3%A9er-une-app-aircall-sur-nimporte-quelle-instance)
> Fix Aircall requests when user is not defined

- setup.py
Bump version of connectors from 0.34.0 to 0.35.0
> bump version to 0.35.0

- setup.py
- tests/oracle_sql/test_oracle_sql.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/google_my_business/google_my_business_connector.py
- toucan_connectors/micro_strategy/data.py
- toucan_connectors/snowflake/snowflake_connector.py
- fix too small variable names
- remove useless f-strings
> [lint] fix flake8 issues

- setup.py
Update of version of Toucan-Connectors
> updated to patch version 0.36.1

- tests/trello/test_trello.py
- toucan_connectors/trello/trello_connector.py
> Trello connector implements "filter" param

- setup.py
Update version of Toucan-Connectors to 0.37.1 to accept a patch that provides a bug fix for Aircall template.
> update version to v0.37.1

- setup.py
Patching Toucan-Connectors with elastic search schema
> bump version to 0.37.2

- setup.py
Removes sensitive information from tests and such
> bump connector version to 0.37.3

- tests/mongo/test_mongo.py
- tests/mysql/test_mysql.py
- tests/test_connector.py
- toucan_connectors/__init__.py
> feat: add info to know if a connector implements `get_status`

- toucan_connectors/google_big_query/google_big_query_connector.py
Just a label error
:x:
* ~[ ] Unit tests for the changes exist~
* ~[ ] Documentation reflects the changes where applicable~
> BigQuery :: fix scopes label

- setup.py
Version change for toucan-connectors
Contains bug fix for mongoDB connector test
Contains new Revinate connector
> bump version to 0.39.0

- setup.py
Update to params in snowflake connector (patch)
> chore(bump): bump patch version to 0.39.1

- setup.py
> chore(dep): fixing snowflake CI errors

- tests/aircall/helpers.py
- tests/aircall/test_aircall.py
- tests/revinate/test_revinate.py
- tests/rok/test_rok.py
- toucan_connectors/__init__.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/facebook_insights/facebook_insights_connector.py
- toucan_connectors/google_credentials.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/toucan_connector.py
Bumping version of black and lint the files that need to be linted.
Contains bump of connectors version so can rebuild.
> chore(deps): bump black and re-lint

- toucan_connectors/google_analytics/google_analytics_connector.py
- toucan_connectors/google_big_query/google_big_query_connector.py
- toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
- toucan_connectors/micro_strategy/micro_strategy_connector.py
- toucan_connectors/odata/odata_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
Add `target="_blank"` in all external links references
https://toucantoco.slack.com/archives/CF9BKPMJR/p1596789359058900
> Add target blank on links

- setup.py
- toucan_connectors/toucan_connector.py
Removes an extraneous function.
> fix(gsheets2): removed extraneous function

- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
Added a keyword argument after input on robustness of the code 'upstream' of the connectors. This prevents errors from occurring stemming from a positional argument being passed in.
> feat(oauth): made factory kwargsful

- .github/workflows/ci.yml
Simply remove codecov, as it's redundant with Sonar
> build: remove codecov

- setup.py
Updated Toucan Connectors version in setup.py
> Chore(version): bump-v0.42.0

- doc/connectors/ROK.md
- quickstart/rok/quickstart_rok.py
- setup.py
- tests/rok/test_rok.py
- toucan_connectors/rok/rok_connector.py
Implementation of a JWT based authentication method with ROK: 
Live data mode data source now requires a secret (to be provided by ROK) to authenticate users and retrieve data. 
The authentication process is described in the attached document [https://trello-attachments.s3.amazonaws.com/5e1c3818f58aba66fa30fcc0/5f748a3b848ebe1fbd540267/5f63d051d2cac56b5a81aa95033685e2/Proposition_authentification.docx](url)
> ROK Connector: Authentication mode with specific JWT

- setup.py
Bumps connector version to 0.43.4
> chore(version):bump connectors version v0.43.4

- .github/workflows/ci.yml
- toucan_connectors/install_scripts/odbc.sh
I renamed and updated the odbc driver install script.
> fix(odbc-connector):fixed the shell script for driver's installation

- toucan_connectors/install_scripts/odbc.sh
Fixed the odbc install script.
> fixed odbc install script

- setup.py
Bumps connectors version to 0.43.8 to onboard the fix on odbc.sh
> bumps connectors version to 0.43.8

- setup.py
Bumps connectors version to 0.43.9 to onboard the update of odbc.sh script
> chore(version):Bump connectors version to 0.43.9

- toucan_connectors/odbc/odbc_connector.py
A user of the ODBC connector requested that the query field to be the same as in other SQL connectors. 
I improved that by using the sql widget in the pydantic field.
> feat(odbc-connector): enhanced odbc connector query field

- setup.py
> chores(version): bump version number

- setup.py
Bump Toucan Connectors version to V0.44.0
> chore(version): bump toucan connectors v0.44.0

- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
Github organization for the Github Connector authentified user are now available as an enum
> feat(GithubConnector):make organizations available as enum

- Makefile
Trying to fix the issue with pip in CI.
> fix(CI): temporarly pin pip version to 20.2

- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
Added get_organizations method to retrieve organizations during signup as well as in the datasource form.
> feat(Github Connector): new get_organizations method

- setup.py
Onboards fix on gsheets get_slice method
> chore(versions): bump connectors v0.44.5

- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
Fix small mistake on gsheets2 connector
> fix(gsheets2): page limit +1

- toucan_connectors/github/github_connector.py
Small fixes on Github connector
> fix(Github): default page_limit=10, sleep btw queries

- setup.py
Unpinned snowflake connector's version.
https://trello.com/c/ghSjOMx6/1476-2-etq-dev-je-peux-utiliser-la-derni%C3%A8re-version-du-package-snowflake
> fix(deps): unpinned snowflake connector version

- doc/connectors/http_api.md
- doc/connectors/mongo.md
- toucan_connectors/micro_strategy/micro_strategy_connector.py
- toucan_connectors/mongo/mongo_connector.py
Fixed some broken links in toucan_connectors docs
> doc: fixed broken links or removed them when needed

- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
To improve UX, some changes are needed on the Gsheets connector forms. 
- Update "domain" title to "dataset"
- Fix the "parameter" tooltip
- Change the order of the fields, ID OF THE SPREADSHEET & SHEET TITLE above Load, Live Data etc... in the form
> Improve gsheets connector's form

- setup.py
Bumps connectors version to 0.44.13
> chores(version): bump connectors version 0.44.13

- tests/mssql/test_mssql.py
- toucan_connectors/mssql/mssql_connector.py
Added get_form & init method in MSSQL connector to enable introspection.
> feat(MSSQL): Introspection in MSSQL connectors

- tests/oracle_sql/test_oracle_sql.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
Added introspection in Oracle Data source (only for Tables as Database is set in Connector's form)
> feat(Oracle): Introspection in Oracle Data Source

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR enables the end user to select any existing database in the datasource instead of manually input the name in the form
None.
> feat(snowflake): Add databases list dropdown in the datasource form

- tests/aircall/test_aircall.py
- tests/aircall/test_async_funcs.py
- toucan_connectors/aircall/aircall_connector.py
Added an optional provided token field.
> feat/optionally provide token to aircall connector & add start & end dates in query params

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR enables the end user to select any existing warehouse in the data source form.
None
> feat(snowflake): Add warehouses list dropdown in the data source form

- tests/postgres/test_postgres.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
Trello card : https://trello.com/c/1zt4Vwah/1711-2-impossible-dutiliser-le-connecteur-postgres-environnement-de-test-denodo
> Fix: get form should work even if connect fails

- setup.py
Bump connectors version to 0.45.13
> chores: connectors v0.45.13

- doc/connectors/hubspot.md
- tests/hubspot/test_hubspot.py
- toucan_connectors/__init__.py
- toucan_connectors/hubspot/doc.md
- toucan_connectors/hubspot/hubspot_connector.py
> feat(hubspot): new connector for Hubspot

- doc/connectors/hubspot.md
- toucan_connectors/hubspot/doc.md
- toucan_connectors/hubspot/hubspot_connector.py
This PR aims to clarify the current documentation for the Hubspot connector
* ~~[ ] Unit tests for the changes exist~~
* ~~[ ] Tests pass on CI and coverage remains at 100%~~
> fix(hubspot): improve documentation for Hubspot connector

- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
> feat(httpapi): flatten nested column

- tests/mssql/test_mssql.py
- toucan_connectors/mssql/mssql_connector.py
Add support for interpolating server side values using jinja since they are safe (as opposed to client side values).
> feature(mssql) add support for interpolating server side values

- setup.py
- tests/test_common.py
- toucan_connectors/common.py
Use the same rendering logic as in toucan's frontend.
(Fixes rendering of checkboxes requester variable)
> feat: flatten rendred nested lists in nosql_apply_parameters_to_query

- setup.py
> chore(version): bump version to 0.51.1

- tests/soap/test_soap.py
- toucan_connectors/soap/helpers.py
- toucan_connectors/soap/soap_connector.py
Improving the SOAP connector's response parsing.
> refactor(soap connector): improved response parsing

- tests/test_datasource.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/toucan_connector.py
Update titles and descriptions for http-api datasource following the workshop
/
> refactor(http-api connector): update titles and descriptions for datasource

- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
Made in PP with @raphaelvignes 
Update httpAPI datasource keys order
/
> chore(http-api): update datasource keys order

- tests/mysql/test_mysql.py
- tests/postgres/test_postgres.py
- tests/test_common.py
- toucan_connectors/common.py
Return a more helpful message if the sql query failed on attempts to interpolate the table name.
> feat: add error message when trying to interpolate sql table name

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR adds the support of `get_status` for the Snowflake connector.
None.
* [] Tests pass on CI and coverage remains at 100%
> feat(snowflake): make the snowflake connector be able to test its connectivity

- requirements-testing.txt
- tests/clickhouse/test_clickhouse.py
- tests/mssql/test_mssql.py
- tests/mysql/test_mysql.py
- tests/odbc/test_odbc.py
- tests/postgres/test_postgres.py
- tests/sap_hana/test_sap_hana.py
- toucan_connectors/common.py
- toucan_connectors/micro_strategy/data.py
- toucan_connectors/mongo/mongo_connector.py
This PR freezes black to the latest version (21.4b0); it also fixes some files that were affected by that upgrade
> chore: Update and freeze black version

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR improves the verbosity (and the checks made) for the `get_status` method of the Snowflake Connector.
> fix(snowflake): improve verbosity of get_status

- setup.py
- toucan_connectors/toucan_connector.py
Added a secrets_storage_version attribute to manage changes in the secrets storage method.
> feat: add secrets_storage_version attribute

- setup.py
The v0.51.13 contains the following PRs:
- https://github.com/ToucanToco/toucan-connectors/pull/384  : Add fields to the Snowflake connector to allow runtime injection of Secrets & Tokens keeper.
> chore(version): bump v0.51.13

- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
Made the connector unusable :sweat:
> fix: typo in gsheet connector

- setup.py
> chore(version): bump-v0.51.15

- toucan_connectors/wootric/wootric_connector.py
- update option for Field from lte to le
> fix(wootric): update attribute max to replace lte by le

- setup.py
> chore(version): bump-v0.51.16

- setup.py
Bump connectors version to 0.52.0
> chores: bump connectors version to 0.52.0

- toucan_connectors/toucan_connector.py
restore the function is_oauth2_connector
> fix(oauth2): re-add the function is_oauth2_connector

- toucan_connectors/wootric/wootric_connector.py
number of pages fetch are not number of pages asked
Update number of pages fetched by bulk
> fix(wootric_bulk): error on fetch data

- setup.py
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
> feat(snowflake get_slice): optimized get_slice for snowflake

- setup.py
> chore(version): bump-v0.53.1

- setup.py
> chore(version): bump-v0.53.2

- setup.py
> chore(version): bump-v0.53.3

- toucan_connectors/snowflake/snowflake_connector.py
> fix(snowflake): get_slice now correctly returns a Dataslice

- setup.py
> chores(version): bump version to 0.53.7

- setup.py
Update dependencies for laputa compatability
- requests
- pyjq
> fix(dependencies): pyjq from 2.5.1 to 2.5.2

- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- toucan_connectors/snowflake/snowflake_connector.py
- Rename field for Snowflake form
> fix(snowflake_form): rename field & error

- setup.py
chore(bump-connectors): upgrade to 0.53.9
> chore(bump-connectors): upgrade to 0.53.9

- setup.py
- tests/snowflake_oauth2/conftest.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Fix some fields & method to be able to use the frontend snowflake features.
> feat(snowflake oauth2): add missing methods & attributes to use frontend features

- setup.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Change Snowflake connectors categories to snowflake.
> fix(snowflakes): change category to snowflake

- setup.py
> chores(bump): v0.54.5

- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
Adding measures & log for Snowflake Benchmarking.
> feat(snowflake oauth2): add logs for benchmarking

- setup.py
chore(bump connectors): v0.55.1
> chore(bump connectors): v0.55.1

- setup.py
- tests/sap_hana/test_sap_hana.py
- toucan_connectors/sap_hana/sap_hana_connector.py
> sap_hana : use up to date lib

- setup.py
> chore(bump connectors): 0.55.3

- setup.py
> chore(bump connectors): 0.55.5

- tests/oauth2_connector/test_oauth2connector.py
- toucan_connectors/oauth2_connector/oauth2connector.py
Hi Toucan,
Here is my fix for this bug https://github.com/ToucanToco/toucan-connectors/issues/424
Have a nice day,
Charles
> Oauth2 - Allow integer in token['expires_at']

- doc/metadata.md
- tests/aircall/test_aircall.py
- tests/github/test_github.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/mongo/test_mongo.py
- tests/soap/test_soap.py
- tests/test_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/toucan_connector.py
Split of: https://github.com/ToucanToco/toucan-connectors/pull/445
This PR takes care of enriching the DataSlice object itself. 
In https://github.com/ToucanToco/toucan-connectors/pull/445 we will only take care of the Metadata computation itsefl
> feat(metadata): add metadata in DataSlice

- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
> feat(snowflake): compute metadata

- setup.py
> chore(version): bump to 1.0.0a1

- setup.py
- toucan_connectors/snowflake/snowflake_connector.py
chore(snowflake): adapt get_slice temporarly
> chore(snowflake): adapt get_slice

- setup.py
Upgrade toucan-connectors version to remove alpha mode
> chore(bump): upgrade toucan-connectors version

- setup.py
- Add query_pool (connection_manager)
- Add Metadata for queries
> chore(bump): upgrade toucan-connectors version to 1.1.0

- setup.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/github/github_connector.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/mongo/mongo_connector.py
We need this param otherwise we get a runtime error when trying to call get_slice
This is a hotfix. 
We will push a cleaner way to do this
> fix(getslice): add get_row_count arg

- setup.py
- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_query_manager.py
- tests/test_snowflake_common.py
- toucan_connectors/query_manager.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_common.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Add `describe` method for Snowflake connectors
> feat: add describe method & associated objects in connectors

- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
- Add request before main request to select the database and warehouse
> fix(use_database_warehouse): add request to use the database and warehouse

- setup.py
> chore(bump): v1.2.2

- tests/hubspot/test_hubspot.py
- toucan_connectors/hubspot/doc.md
- toucan_connectors/hubspot/enums.py
- toucan_connectors/hubspot/hubspot_connector.py
Behavior of change: Hubspot works
- Add mandatory scope in hubspot/doc.md
- Update all route 
- Remove 2 hubspot endpoint temporary : web-analytics && emails-events
- Remove legacy mode
> fix(hubspot): update URL and method to get result + remove legacy mode

- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
Check if the connection use the database or warehouse in DataSource
If not, execute a query to change it
> feat(optimize_connection_manager): check if connection use good database and/or warehouse

- setup.py
Upgrade toucan-connectors version
> chore(bump): upgrade version from 1.2.2 to 1.2.3

- toucan_connectors/oauth2_connector/oauth2connector.py
Update method signature to save secret with a new param **kwargs if we need to save or load others informations
> fix(duplicate_small_app): update method signature to save secret

- setup.py
Upgrade version from 1.2.3 to 1.2.4
> chore(bump): upgrade version from 1.2.3 to 1.2.4

- setup.py
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
Remove pandas_gbq to replace by google.bigquery dependency
With pandas_gbq we have a security breach and we need to remove it
> feat(google_bigquery_new): new method to retrieve data in bigquery with pandas

- setup.py
chore(bump): upgrade version to 1.2.5
> chore(bump): upgrade version to 1.2.5

- setup.py
- toucan_connectors/install_scripts/odbc.sh
- toucan_connectors/install_scripts/oracle.sh
Fetch connector resources from public-package.toucantoco.com instead of extern sources
> odbc-oracle :: use public packages toucan

- setup.py
> chore(bump): upgrade to 1.2.9

- setup.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
Fix issue https://toucantoco.atlassian.net/browse/TCTC-488 
-> Add database & warehouse connection key.
> fix: add database & warehouse in snowflake's connection key

- setup.py
- toucan_connectors/snowflake_common.py
Fix an incorrect type name in snowflake_common
> fix: wrong type name in snowflake_common

- setup.py
- toucan_connectors/toucan_connector.py
add a arbitrary dict to store metadatas in dataslices.
> feat(dataslice): add a arbitrary dict to store metadatas in dataslices.

- setup.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
Replace snowflake type mapping provided by snowflake does not contain "int". 
We must reflect that in `snowflake_common.py`
> fix(snowflake_common): type mapping

- tests/github/conftest.py
- tests/github/test_github.py
Fixes the tests that @luc-leonard noted were failing from November 18th.
> test(github): fix extraction dates and correct PR count

- setup.py
- sonar-project.properties
> chore: v1.3.29

- doc/connectors/one_drive.md
- tests/one_drive/test_one_drive.py
- toucan_connectors/one_drive/one_drive_connector.py
**WARNING :** **Please review #511 first**
Hi Toucan,
Here is my PR to allow conceptors to retrieve data from tables instead of sheets.
Now, conceptors will be able to deal with Excel that contains multiple tables in one sheet !
> feat(one drive): append multiple tables

- setup.py
- sonar-project.properties
- Bump from 1.3.29 to 1.3.30
Changes comming from this [PR](https://github.com/ToucanToco/toucan-connectors/pull/512)
> chore: v1.3.30

- setup.py
- sonar-project.properties
- Bump from 1.3.31 to 1.3.32
Changes comming from this [PR](https://github.com/ToucanToco/toucan-connectors/pull/514)
> chore: v1.3.32

- setup.py
Bump connectors version 1.3.33
> chore: version 1.3.33

- tests/postgres/test_postgres.py
- toucan_connectors/postgres/postgresql_connector.py
Hi Toucan,
Here is my PR to check the connection for Postgres.
I used the same logic than MySQL Connector.
**NOTE :**
I tryed to catch `psycopg2.errors` but `pgcode` is empty. So I dealt with the error message.
More infos here : https://www.psycopg.org/docs/errors.html#module-psycopg2.errors
> feat(postgres): add connector.get_status()

- tests/redshift/test_redshift.py
- toucan_connectors/redshift/redshift_database_connector.py
> feat(Redshift): add context manager

- setup.py
- sonar-project.properties
Bump connectors v1.3.36 to onboard redshift's connector changes.
> chore: version 1.3.36

- setup.py
- sonar-project.properties
Bump from 1.3.37 to 1.3.38 
Added dates parsing on onedrive connectors from : https://github.com/ToucanToco/toucan-connectors/pull/526
> chore: bump from 1.3.37 to 1.3.38

- tests/redshift/test_redshift.py
- toucan_connectors/redshift/redshift_database_connector.py
> update redshit connector

- setup.py
- sonar-project.properties
Bump to 1.3.39 for redshift connector.
> chore: v1.3.39

- setup.py
- sonar-project.properties
- tests/redshift/test_redshift.py
- tests/test_sql_query_helper.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake_common.py
- toucan_connectors/sql_query_helper.py
Revert some changes inadvertently removed in https://github.com/ToucanToco/toucan-connectors/pull/543
but with better naming and a comment to know why it's there.
> fix(sql): don't run count for DESCRIBE or SHOW queries TCTC-1567

- doc/DataSlice.md
- toucan_connectors/snowflake_common.py
- toucan_connectors/toucan_connector.py
- Add and clarify the doc for the DataStats class
More details from this card : [TCTC-1417](https://toucantoco.atlassian.net/jira/software/c/projects/TCTC/boards/18?modal=detail&selectedIssue=TCTC-1417)
> doc: format the DataStats model [TCTC-1417]

- toucan_connectors/google_sheets/google_sheets_connector.py
We need this to be able to call the right pizzly integration :)
> chore(google-sheets): add Pizzly integration identifier

- tests/google_sheets/test_google_sheets.py
- tests/google_sheets/user-infos.json
- toucan_connectors/google_sheets/google_sheets_connector.py
Added the get_status for the new google-sheet connector
> feat(google-sheets): implement get_status for new google-sheets connector TCTC-1672

- CHANGELOG.md
- setup.py
- sonar-project.properties
Release of the new google sheets connector
> chore: v3.0.0

- setup.py
- sonar-project.properties
- toucan_connectors/snowflake_common.py
Fix the issue on duplicate columns displayed in Snowflake's Graphical interface.
> fix(snowflake): get model query

- toucan_connectors/google_sheets/google_sheets_connector.py
IndexError and KeyError can both happen in cell_format util. Just catch the exception.
TCTC-2274 https://toucantoco.atlassian.net/browse/TCTC-2274
> fix(gsheet): cell_format is also subject to IndexError TCTC-2274

- setup.py
- sonar-project.properties
- Creation of a new connector (AWSAthena)
> chore: bump from 3.2.1 to 3.3.0

- setup.py
- sonar-project.properties
* fix(sql connectors): set `datetime` dtype when needed (#591)
* build(deps): remove useless sqlalchemy dependency (#593)
* feat(google BigQuery): Add support for array query parameters TCTC-1447 (#594)
* refactor(bigquery): Delegate parameter handling to the library (#596)
> chore: v3.5.0

- setup.py
- sonar-project.properties
> chore: v3.6.0

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> chore: v3.12.0

- tests/postgres/test_postgres.py
- tests/redshift/test_redshift.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/redshift/redshift_database_connector.py
- added default db for postgres
- added default db for redshift
- added a new status check for request on default database
- adapt code & tests accordingly to changes for postgres and redshift
> feat: default db check for postgres and redshift

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
* Add attributes & methods to big query connector for graphical selection
> chore: 3.15.1

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Bump connectors 3.15.2 for big query graphical selection.
> chore: bump connectors 3.15.2

- tests/test_common.py
- toucan_connectors/common.py
Some step's can be tuples. We need to be able to render them
> Render Tuples

- tests/redshift/test_redshift.py
- toucan_connectors/redshift/redshift_database_connector.py
Removing connection manager how was responsible for some weird hanging connections.
> Redshift connector does not work with ConnectionManager

- CHANGELOG.md
- pyproject.toml
> chore: v3.16.0

- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
Enable Athena's Graphical Interface.
> feat(athena): graphical interface

- tests/docker-compose.yml
- tests/mysql/fixtures/world.sql
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
Enable Mysql Graphical Selection ITF
> feat(mysql): graphical selection

- CHANGELOG.md
- pyproject.toml
- toucan_connectors/mysql/mysql_connector.py
Bump to v3.17.0 to enable Mysql & Athena connectors Graphical Selection
> chore: v3.17.0

- .github/workflows/ci.yml
I saw that Sonar was no longer triggered in our CI :scream:
> ci: re enable sonar

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- toucan_connectors/mysql/mysql_connector.py
* Frontend-crafted queries come with " quoting character. As long as queries are crafted by frontend we need to replace these characters.
> fix: mysql quoting character

- poetry.lock
- pyproject.toml
- sonar-project.properties
- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
* Remove useless default schema from Athena connector.
> chore(athena): default schema

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/mysql/mysql_connector.py
fix(mysql): allow deprecated follow_relations attribute
> fix(mysql): allow deprecated follow_relations attribute

- CHANGELOG.md
- pyproject.toml
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
> Check if query is specified mysql

- CHANGELOG.md
- pyproject.toml
- tests/test_pandas_translator.py
- toucan_connectors/pandas_translator.py
> fix(conditions/pandas): Fix requires_number decorator 

- CHANGELOG.md
- pyproject.toml
> chore: v3.19.0

- CHANGELOG.md
- pyproject.toml
> chore: bump from 3.19.0 to 3.20.1

- tests/awsathena/test_awsathena.py
- tests/test_connector.py
- toucan_connectors/awsathena/awsathena_connector.py
- toucan_connectors/toucan_connector.py
> fix(athena): Fix pagination values TCTC-3822

- CHANGELOG.md
- pyproject.toml
> chore: v3.20.3

- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
Athena variables are ended with a ;
> [Athena] missing ; for variables

- CHANGELOG.md
- pyproject.toml
> Release v3.20.4

- CHANGELOG.md
- pyproject.toml
- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
Fixed order of OFFSET and LIMIT parameters in Athena
> Fix athena pagination

- poetry.lock
- pyproject.toml
A bump that include these changes : https://github.com/ToucanToco/toucan-connectors/pull/669
> chore: bump from 3.20.5 to 3.20.6

- CHANGELOG.md
> fix: update the CHANGELOG

- .github/dependabot.yml
- .github/workflows/publish.yml
> chore(ci): Set up PyPI release automation + dependabot TCTC-1590

- CHANGELOG.md
- pyproject.toml
> chore: v3.21.1

- toucan_connectors/__init__.py
> feat: get version of toucan-connector

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> chore: loosen lxml constraint to be compatible with python-saml3

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore: v3.22.3

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore:v3.23.1

- .github/dependabot.yml
> chore(ci): Add dependabot on GH actions

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore: v3.23.4

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> fix: Pin google-cloud-bigquery ^2

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- toucan_connectors/google_big_query/google_big_query_connector.py
> fix(deps): Bump google-cloud-bigquery >=3

- CHANGELOG.md
- pyproject.toml
> chore: v3.23.5

- CHANGELOG.md
- pyproject.toml
> chore: v3.24.0

- Makefile
- poetry.lock
- pyproject.toml
- tests/http_api/test_http_api.py
- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_common.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Work items:
* Stop using SnowflakeCommon
* Stop using ThreadPools
* Stop using connection pools
* Add mypy checks
TCTC-4601
> refactor(snowflake): Simplify the snowflake connector TCTC-4601

- CHANGELOG.md
- pyproject.toml
> chore: v3.25.0

- doc/DataSlice.md
- doc/PaginationInfo.md
- tests/awsathena/test_awsathena.py
- tests/mongo/test_mongo.py
- tests/redshift/test_redshift.py
- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_connector.py
- tests/test_pagination.py
- tests/test_snowflake_common.py
- toucan_connectors/awsathena/awsathena_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/pagination.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_common.py
- toucan_connectors/toucan_connector.py
Work items:
* Move pagination out of DataStats and add a required PaginationInfo attribute to the DataSlice class
* Adapt tests
TCTC-3310
> refactor: Refactor pagination info TCTC-3310

- sonar-project.properties
> deps: added the version of toucan-connectors to the sonar-project.properties v4.0.0

- poetry.lock
- pyproject.toml
- ci: sync format black & isort
- feat: updated lock for python version
> ci: sync format black & sort

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
bump toucan-connectors from 3.23.5 to 3.23.6
See : https://github.com/ToucanToco/toucan-connectors/pull/800
> chore: bump toucan-connectors from 3.23.5 to 3.23.6

- CHANGELOG.md
- toucan_connectors/google_sheets/google_sheets_connector.py
See : https://github.com/ToucanToco/toucan-connectors/pull/800
> feat: add an option to render date-time when reading a sheet

- CHANGELOG.md
- toucan_connectors/google_sheets/google_sheets_connector.py
We want the date as float selected as default
> feat: we want the date-as-float selected as default

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore: bump connectors from 3.23.6 to 3.23.7

- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
> fix(gbq): Support building a DB model for projects with datasets in distinct locations TCTC-4879

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- sonar-project.properties
Added a new file based connector : [Peakina](https://github.com/ToucanToco/peakina)
> chore: v4.2.0

- CHANGELOG.md
- toucan_connectors/__init__.py
- Export peakina as a connector
> fix: export peakina as connector

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/__init__.py
> chore: bump 4.2.0 to 4.2.1

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore: bump from 4.2.1 to 4.2.2

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
> fix(snowflake): In get_model(), only list all databases if db_name is not specified

- CHANGELOG.md
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
> feat(backport): allow empty field mysql ssl [TCTC-5306]

- CHANGELOG.md
- pyproject.toml
> chore: v3.23.10

- poetry.lock
- pyproject.toml
> chore: bump peakina 0.10.0

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
> chore: bump toucan-connectors  to v4.4.1

- tests/test_common.py
- toucan_connectors/common.py
> feat: toucan-connector should not deal with VOID into filter steps, let's keep that removal loggic to weaverbird  [TCTC-5480, TCTC-6102]

- toucan_connectors/http_api/http_api_connector.py
Add logs to be able to debug issues such as [this one](https://toucantoco.slack.com/archives/C823R095H/p1686575528508869) more easily
I put the info in the message and not the kwargs because it is easier for the care team to read them that way in kibana
> feat: enhance http api connector logs

- CHANGELOG.md
- toucan_connectors/mysql/mysql_connector.py
Similar to this old fix for snowflake : https://github.com/ToucanToco/toucan-connectors/pull/574
> fix: duplicate columns on mysql [TCTC-6141]

- CHANGELOG.md
- pyproject.toml
- toucan_connectors/mysql/mysql_connector.py
(backport of https://github.com/ToucanToco/toucan-connectors/pull/1131)
> fix(lts): duplicate columns on mysql [TCTC-6141]

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tests/conftest.py
A pick from https://github.com/ToucanToco/toucan-connectors/pull/1183
to have this fix on master too.
> fix: pyyaml deps bump

- CHANGELOG.md
- pyproject.toml
> chore: bump from 4.7.1 to 4.7.2

- sonar-project.properties
> update a missing version update on sonar properties

- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
This is a backport of a feature available on V3
> feat(backport): google big query database selection much faster [TCTC-6113] (#1126) [TCTC-6473]

- tests/google_sheets/test_google_sheets.py
- toucan_connectors/google_sheets/google_sheets_connector.py
> fix: replace empty '' by numpy.nan on column for google-sheet  [TCTC-6530]

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Contains this fix for LTS : https://github.com/ToucanToco/toucan-connectors/pull/1246
> chore: bump to v3.23.17

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Release https://github.com/ToucanToco/toucan-connectors/pull/1273
> chore: v4.8.0

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Includes : https://github.com/ToucanToco/toucan-connectors/pull/1287
> chore: bump from 4.8.1 to 4.9.0

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
This bump includes : https://github.com/ToucanToco/toucan-connectors/pull/1293
> chore: bump from 4.9.0 to 4.9.1

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Contains : https://github.com/ToucanToco/toucan-connectors/pull/1308
> chore: bump 4.9.1 to 4.9.2

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Backport #1330 for 3.23 branch
> fix(3.23, snowflake): pin oscrypto to solve ongoing issue with OpenSSL 3.10

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Due to a known bad regex in oscrypto, dependency sued by snowflake_connector
> fix(snowflake): pin oscrypto to solve ongoing issue with OpenSSL 3.10

- pyproject.toml
- sonar-project.properties
- toucan_connectors/databricks/databricks_connector.py
- toucan_connectors/install_scripts/databricks.sh
LTS port of Databricks connector fix (#1344)
> chore: v3.23.20

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/databricks/databricks_connector.py
Otherwise, validation on save (when a secret string is not deciphered) is impossible
> fix(databricks): default value for password (LTS) TCTC-7172

- CHANGELOG.md
- toucan_connectors/install_scripts/oracle.sh
> fix(current): oracle install script

- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
With a very simple query, that works even without any table. When testing, I measured that the status check took less than 1s.
> feat(google_big_query): actual connection check

- tests/test_common.py
- toucan_connectors/common.py
> fix: duplicate cols in SQL

- .github/workflows/ci.yml
- Makefile
> ci: fix python 3.12 run

- CHANGELOG.md
- tests/hubspot_private_app/test_hubspot.py
- toucan_connectors/hubspot_private_app/hubspot_connector.py
Add ability to select custom properties on objects.
Example :
> feat(hubspot): allow to query specific properties [TCTC-9025]

- .github/workflows/ci.yml
- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
Also introduce integration tests for GBQ
> fix(biquery): enforce int and float dtypes [TCTC-9419]

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
Contains the bugfix for the jinja injection vulnerability
> chore: v7.4.1
