- doc/mysql.md
- setup.py
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
Add 2 new datasource options (only for mysql connector for now) : 
- `parameters` (dict, default `None`) : parameterized query (you will need a query with `%(param_name)s`)
- `follow_relations` (bool, default `True`) : specific to mysql connector which merges data from foreign key relations → now you can disable this behaviour
> MySQL :: parameterized query

- setup.py
- tests/mongo/test_mongo.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/google_analytics/google_analytics_connector.py
- toucan_connectors/mongo/mongo_connector.py
Remove a dictionary key if it's value has a missing parameter.
This is used to support the `__VOID__` syntax, wich specific to
Toucan Toco use of mongo : cf. https://bit.ly/2Ln6rcf
> Feature :: support missing parameters in mongo connector

- setup.py
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
Used for `marques-avenue`. Before we used to the method `_clean_response` defined [here](https://github.com/ToucanToco/laputa/blob/marques-avenue/app/connectors/mysql_connector.py#L42) and called [here](https://github.com/ToucanToco/laputa/blob/marques-avenue/app/connectors/sql_connector.py#L68)
Since we want to remove the `follow_relations`, I decided to create a proper method (which may be moved to all dfs in the future if needed)
> Feature :: decode bytes columns for MySQL

- doc/connectors.md
- doc/http_api.md
- setup.py
- tests/http_api/test_http_api.py
- toucan_connectors/__init__.py
- toucan_connectors/http_api/http_api_connector.py
Avant : HttpAPI connector était dans Laputa, ne supportait pas le passage de paramètres de la front config
Maintenant : HttpAPI connector est dans Laputa et dans toucan-connector, support le passage de paramètres par le frontend
> features :: HttpAPI connector

- setup.py
- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
Before : auth object is wrongly associated to the data source
After : auth object is associated to connector
> Hotfix :: auth on http api connector, not datasource

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
For connector mongo, fix handle_missing_params for query like : 
```
{'$project': {'b':{'$divide' : ['$c', '$a']}}}
```
>  Hotfix :: mongo with divide

- doc/http_api.md
- setup.py
- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
After removing the 'template' option at the provider level, we realised it was used.
> Hotfix :: httpAPI connector, add support for template and fix json

- doc/http_api.md
- setup.py
- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
Context: https://trello.com/c/pNyoVpRs/1220-etq-skf-je-peux-connecter-%C3%A0-mes-donn%C3%A9es-via-une-api-avec-une-0aut2-authentication-05
> http api connector :: Add support for oauth2 "backend application flow"

- setup.py
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/common.py
- toucan_connectors/google_big_query/google_big_query_connector.py
Add scopes support https://github.com/ToucanToco/toucan-connectors/issues/60
> google big query :: add scope parameter

- setup.py
- tests/test_connector.py
- tests/test_retry_policy.py
- toucan_connectors/toucan_connector.py
By default, behaviour is unchanged, there's no retry but each connector
now accepts a `retry_policy` paramater that supports the following
customization:
- `max_attempts`: the maximum number of retries before giving up
- `max_delay`: delay, in seconds, above which we should give up
- `wait_time`: time, in seconds, between each retry.
For instance, you can create a new connector that will retry at most 5
times if `get_df` fails by doing:
```python
my_connector = MyConnector(name=u'foo', retry_policy={'max_attempts': 5})
```
> Implement a retry policy on connectors.

- setup.py
- tests/odata/test_odata.py
- toucan_connectors/odata/odata_connector.py
cf. #z-connexion-odata and https://github.com/tuomur/python-odata/issues/22
The bug happened on https://demos.shuttle-cloud.com/MASTER.DataAPI/shut_repo-odata-en-service/ : 
- https://demos.shuttle-cloud.com/MASTER.DataAPI/shut_repo-odata-en-service/$metadata works :heavy_check_mark: 
- https://demos.shuttle-cloud.com/MASTER.DataAPI/shut_repo-odata-en-service/$metadata/ doesnt (500 error) :x:
> Hotfix :: OData connector

- tests/test_connector.py
- toucan_connectors/toucan_connector.py
Miswriting of the `offset` and `limit` option in `ToucanConnector.get_slice`:
```python
return result[offset:limit] 
```
Returned the correct result only when `offset=0`
👉  The `offset` option of `get_slice` was not tested 😱
> Fix :: pagination of get_slice connectors method

- tests/test_connector.py
- toucan_connectors/toucan_connector.py
*Before*
when `limit` is `none`, the addition `offset+limit` raised an error
*now*
when `limit` is `none` it is not apply
> Fix :: get_slice with no limit

- Makefile
- setup.cfg
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
I had an issue on laputa where my test would be ok alone but ko with a test run before it.
In fact, it's because the previous collection was not considered as dropped in the new connector (because of the LRU cache key was the same) and it targetted the wrong one
> Fix :: cache validation should be proper to a given connector instance

- setup.py
- tests/mongo/test_mongo_translator.py
- toucan_connectors/common.py
Permissions may contain backticks because they are pandas.query like expressions.
> Handle backticks in permissions

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Implement a `get_df_with_regex` method, to be able to search in data.
---
Before discussions (https://github.com/ToucanToco/toucan-connectors/pull/115#issuecomment-536872924): 
Implements a `search` method, based on these rules:
https://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html
Search proceeds using one query for each rule. It stops as soon as the number of required results (`limit`) has been reached.
This will be useful for database discovery with autocomplete.
> Mongo :: get_df_with_regex method

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
For mongo connector, apply permissions in the first `$match` of the pipeline.
> Mongo connector :: apply permissions early

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Instantiate `MongoClient` with kwargs rather than with a connection string built from the connector parameters.
It means that it will be easier to add any supported `MongoClient` kwargs at the `MongoConnector` level.
It also means that we can use a connection string in the `host` field and leave out all the other parameters. In the end we can natively support a lot more connections options than we cover with the few parameters that we have explicitly listed in `MongoConnector`. cf. https://docs.mongodb.com/manual/reference/connection-string/
And more specifically this means that when you create a new MongoDB Atlas cluster, you can just copy and paste the connection string that is given by Atlas into our configurations files.
> Mongo :: instantiate MongoClient with kwargs instead of building a connection string

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
Need to execute a special instruction before queries.
` A warehouse must be specified for a session and the warehouse must be running before queries and other DML statements can be executed in the session.`
source : https://docs.snowflake.net/manuals/sql-reference/sql/use-warehouse.html
> Snowflake :: fix with use warehouse

- .circleci/config.yml
- setup.py
- toucan_connectors/install_scripts/__init__.py
- toucan_connectors/install_scripts/azure_mssql.sh
- toucan_connectors/install_scripts/databricks.sh
- toucan_connectors/install_scripts/oracle.sh
The goal is to be able to run these scripts from within our docker image (at runtime or in a `RUN` dockerfile step) to install these extra dependencies.
> Add shell install scripts for some connectors

- setup.py
The current package 0.28.0 does not include the bash scripts to install the connectors' system dependencies.
This PR should fix it.
> MANIFEST.IN :: add missing bash scripts

- tests/google_analytics/test_google_analytics.py
- tests/google_big_query/test_google_big_query.py
- tests/google_spreadsheet/test_google_spreadsheet.py
- tests/mongo/test_mongo.py
- tests/sap_hana/test_sap_hana.py
- toucan_connectors/auth.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/dataiku/dataiku_connector.py
- toucan_connectors/google_analytics/google_analytics_connector.py
- toucan_connectors/google_big_query/google_big_query_connector.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/google_credentials.py
- toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/micro_strategy/micro_strategy_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/odata/odata_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/sap_hana/sap_hana_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
Use `pydantic` to improve schemas to be used by a form builder.
This PR proposes to introduce 2 new custom elements:
-  a new 'sql' `widget` (next to the already implemented 'json' widget) and to be used as a SQL text editor in the UI
- an `examples` key to list example values and to be used as placeholder in the UI
At the moment it does not cover the following connectors:
- adobe
- adobe_analytics
- elasticsearch
- facebook_insights
- google_my_business
- toucan_toco
- trello
- wootric
> Feature :: Improve schemas

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Before : when passing a complete connection URI, some parameters are overwritten with None because of the default values. `pymongo` crashes when `bool` parameters are passed as `None`
Now: filter out `None` parameters from the arguments passed to `pymongo.MongoClient`
> Mongo :: Filter out optional parameters from MongoClient init

- setup.py
- tests/aircall/test_aircall.py
- tests/conftest.py
- tests/google_sheets/test_google_sheets.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/toucan_connector.py
Improve Aircall Datasource:
- Manage pagination: loop over API pages
- Add a limit option to limit the number of results
- Add a query parameter to be able to add query parameters
For testing purposes, we add the expected BEARER_API_KEY environment variables in fixtures
> Aircall :: Manage pagination and query parameters

- MANIFEST.IN
- setup.py
I don't know how packages on PyPI got the png, but when I build the packages locally I can't get them inside the wheel or the tar.gz, nor when pip installing via the github url.
I followed the same approach we use on toucantoco/laputa.
> include PNG (and all other static files) on make build

- doc/connectors/oracle_sql.md
README:: OracleSQL connector instructions 
Description: 
Updated the readme to provide the easiest method to install oracle connector package
> README :: OracleSQL instructions

- requirements-testing.txt
- setup.cfg
- tests/aircall/test_aircall.py
- toucan_connectors/mongo/mongo_connector.py
Before this PR, a $facet stage was added as the first step of the
mongo aggregationn pipeline of the datasource query. This lead to:
- bugs when the original query includes itself a $facet stage, as
$facet stages cannot be nested
- performance downgrade as we execute twice the main query, instead
of executing it once and facetizing the query at the end, as it is
proposed in this PR
> mongo :: change implementation of the query facetizing in get_slice()

- tests/hive/test_hive.py
They hang for an unknow reason on GitHub CI.
I suggest to skip them and investigate in order not to block other PRs.
None
> Skip Hive tests temporarly

- .github/workflows/ci.yml
CI build is a bit slow due to the `docker pull` of all the required images.
They should be cached to avoid re-pulling them at each build.
None
> Set up cache for docker images in CI

- tests/aircall/test_aircall.py
- tests/aircall/test_helpers.py
- toucan_connectors/aircall/helpers.py
Replace null values with the label 'NO TEAMS' in the column "team" of the
"calls" dataset (in coherence with what we do for the "users" dataset).
> Aircall: fix "calls" datasource

- doc/connectors/mongo.md
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Trying to `get_slice` on a very large collection (25M rows) was _very_ slow (1min30).
This is caused by the count facet, which forces mongo to scan all docs regardless of the limit.
I suggest we limit this to a somewhat high value, but that doesn't impact too much performance.
I choose 1M, because it took 3s on my local mongo, and seems a nice threshold above which the exact count is not very relevant.
> Prevent mongo connector to count more than 1M rows

- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
Replaces the strict baseroute validation in the HTTP connector with a more permissive one. This allows a user to create a connector that has no top domain.
Please see [https://trello.com/c/EuUpirXG/4119-as-an-app-builder-i-can-use-a-connector-with-an-url-with-no-top-level-domain](https://trello.com/c/EuUpirXG/4119-as-an-app-builder-i-can-use-a-connector-with-an-url-with-no-top-level-domain)
> Fix ::: HTTP connector ::: no top level domain

- setup.py
Bug fix when concepteur does not put in a top domain in url for HTTP connector
[Trello card](https://trello.com/c/EuUpirXG/4119-as-an-app-builder-i-can-use-a-connector-with-an-url-with-no-top-level-domain)
> version bump :: 0.36.2

- setup.py
This PR fixes a bug that makes tests in GitHub actions fail: https://github.com/snowflakedb/snowflake-connector-python/issues/324
It sets the requests dependency version to less than 2.24.0
> Fix(dependencies) : fixing bug in Github actions

- tests/aircall/test_async_funcs.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/http_api/http_api_connector.py
Adds an async retry policy if an error is returned by Aircall.
- So far we have three tries that fire once every second
- If things keep going badly, an exception is raised
- Logging was also added to the Aircall calls
[Trello Card](https://trello.com/c/2z20DaPa/506-5-etqc-je-peux-cr%C3%A9er-une-app-aircall-de-fa%C3%A7on-consistante)
> fix(aircall) : for retrying Aircall API if error

- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/elasticsearch/elasticsearch_connector.py
- toucan_connectors/http_api/http_api_connector.py
Proposes error message for bad variable in endpoint while configuring datasets retrieved from an HTTP connector
This PR makes the error message more explicit.
NOTE: wording has been changed a little in the error message proposed in this PR.
> fix(error message) :: ETL validation crash in HTTP connector

- setup.py
Bumping version to 0.37.4 with a bug fix on validation in common function used by HTTP connector.
If a bogus variable is used, an exception is raised and will provide a comprehensible error message in the client.
> versioning :: bumping version to 0.37.4

- toucan_connectors/install_scripts/oracle.sh
currently unable to launch `install_scripts/oracle.sh`:
```
...
Preparing to unpack .../libcurl4_7.64.0-4+deb10u1_amd64.deb ...
Unpacking libcurl4:amd64 (7.64.0-4+deb10u1) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.64.0-4+deb10u1_amd64.deb ...
Unpacking curl (7.64.0-4+deb10u1) ...
Selecting previously unselected package libaio1:amd64.
Preparing to unpack .../libaio1_0.3.112-3_amd64.deb ...
Unpacking libaio1:amd64 (0.3.112-3) ...
Setting up libcurl4:amd64 (7.64.0-4+deb10u1) ...
Setting up curl (7.64.0-4+deb10u1) ...
Setting up libaio1:amd64 (0.3.112-3) ...
sh: 1: wget: not found                                 >>>>>>>>>>>>>>>>>>>>>> !!
Couldn't download the file :-(
```
It's related to the [perl …
> install_scripts :: oracle - add missing wget

- tests/mongo/test_mongo.py
Mongo error format seems to differ in some local setups and in the CI (https://github.com/ToucanToco/toucan-connectors/pull/186/checks?check_run_id=941369017)
Fixes #187 
* ~[ ] Documentation reflects the changes where applicable~
> fix(mongo): fix status error format

- setup.py
unpin urllib3 (which was pinned in https://github.com/ToucanToco/toucan-connectors/pull/120) to avoid conflicts in Toucan api with responses 0.10.16
> unpin urllib3

- .coveragerc
- .github/workflows/ci.yml
- .gitignore
- Makefile
- README.md
- sonar-project.properties
To get more insights than just coverage metrics, add Sonar analyser.
Results will be visible on sonarcloud
None
> Add sonar analysis to the repository

- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/__init__.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/toucan_connector.py
Beginning of replacing Bearer API in Google Sheets
- New temporary Google Sheets connector that does not work out-of-the-box yet
- CONNECTOR_REGISTRY now returns a Google Sheets API with auth_flow
property but only when a feature flag is on
- No tests yet ; no documentation yet since once this Google Sheets connector replaces the old one, we'll just modify the old document
- Has a feature flag necessary for Tucana
> feat(oauth): Modified Google Sheets

- Makefile
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
We used to have legacy SQL syntax by default for google big query, which was confusing as the official documentation and most of conceptors are used to writing standard SQL.
This PR changes this by setting standard SQL as the default dialect. Conceptors can still manually select legacy syntax if needed
> fix(gbq): use standard SQL as default query syntax

- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/toucan_connector.py
Passing an access_token and refresh token (if applicable) to the connector.
[https://github.com/ToucanToco/laputa/pull/3574](https://github.com/ToucanToco/laputa/pull/3574)
> feat(googlesheets2): first pass at passing token

- doc/connectors/google_sheets_2.md
- tests/google_sheets_2/test_google_sheets_2.py
- tests/test_common.py
- toucan_connectors/__init__.py
- toucan_connectors/common.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/toucan_connector.py
Contains @testinnplayin's work to create a new Google Sheets connector, that can use provided OAuth2 secrets.
Secrets are to be acquired and stored outside of this project scope, and provided before doing any data request using the `set_secret` method.
Any connector that will need such secrets will be flagged with `authFlow: "oauth2"`
> New Google Sheets connector

- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/mongo/test_mongo.py
- tests/mysql/test_mysql.py
- tests/test_common.py
- tests/test_connector.py
- toucan_connectors/common.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/toucan_connector.py
Implement the get_status method for the new google sheets connector, and returns the email account associated with the secrets in the status message.
Opportunistic improvement: introduce a dataclass `ConnectorStatus` to ease the implementation of future `get_status` methods in other connectors. 
This will only require a minor change if `get_status` consumers wants a dict instead: calling its `to_dict` method.
> feat(googlesheets2): Status check

- doc/connectors/google_sheets_2.md
- setup.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
This adds a new property to the Google Sheets 2 connector : `auth_flow_id`, which behaves a lot like the old `bearer_auth_id`. It's used as an identifier for the Google Sheets 2 connector instead of the connector's name, which can be modified by the user.
This renders the oauth dance more robust because 1) we no longer rely on a property that can be changed at any moment by the user and 2) it prevents fan out throw several collections when a user updates their connector's name.
> chore: added auth_flow_id to Google Sheets 2

- doc/connectors/google_sheets_2.md
- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/test_connector.py
- toucan_connectors/__init__.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/toucan_connector.py
Passes secrets as a factory function to Google Sheets 2 connector.
Secrets will no longer be visible in the front-end as a potential input in the connector configuration modal.
NOTE:
I am aware that the 'bag' that contains kwargs is checked in a stupid way but the signature object of the inspect module can't be used in 3.6 like in 3.7 and 3.8 probably due to the fact that we have an abstract function in the way (`_retrieve_data` inside the `ToucanConnector`). This is a workaround up until the time we drop 3.6 support. It's to prevent `secrets` being passed to connectors that don't use it and thus provoking an error.
NOTE:
`base_route` should probably be a class property but that should probably be a different PR since it should be generalized throughout the app. As such, we have merely …
> feat(gsheets2): passed secrets as param

- doc/connectors/google_sheets_2.md
- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
By default google sheets applies the decimal separator defined in the gsheet locale.
We want values such as "," to be correctly interpreted so we added the parameter valueRenderOption=UNFORMATTED_VALUE' to the URL used to retrieve data in the connector
> feat(gsheets2): retrieve unformatted values instead of formatted ones

- setup.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/oauth2_connector/test_oauth2connector.py
- tests/test_connector.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/google_sheets_2/doc.md
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/oauth2_connector/oauth2connector.py
- toucan_connectors/toucan_connector.py
Some connnectors need to be configured when they are instanciated (eg. Postgres needs an hostname, etc.)
Some connectors need to be configured prior to instanciation, because such config is instance wide. eg GoogleSheets2 needs a client_secret, and a client_id. Without those, it is not possible to instanciate a connector.
This PR adds a method get_connector_config_form, optional, at the class level for ToucanConnectors subclasses. it also add a function get_connector_config_form(cls) that dispatches call to  the appropriate class.get_form.
I also separated the config part of the OAuth2Connector in a Pydantic model.
> Add a get_connector_config_form method to connectors

- toucan_connectors/__init__.py
I changed Aircall Connector's name in CONNECTORS_REGISTRY of toucan_connectors __init__.py. 
Previously was: AircallConnector, now Aircall.
> Fix(Aircall):Change Aircall Connector's name

- setup.py
- toucan_connectors/aircall/aircall_connector.py
#182  Change Summary
Aircall Connector build_authorization_url() can now accept and transfer kwargs to oAuth2Connector.build_authorization_url
> added kwargs in build_authorization_url

- doc/connectors/http_api.md
- requirements-testing.txt
- setup.py
- tests/http_api/test_http_api.py
- toucan_connectors/common.py
- toucan_connectors/http_api/http_api_connector.py
This PR adds the support of XML in HttpAPI connector
The HttpApi connector can be configured to parse XML responses using xmltodict package. 
* A ResponseType field was added to the connector's configuration, options are xml or json
* An XpathSchema was added to the Data Source, in order to receive the xpath string the user might want to use to parse the xml content of the response
* Once converted to a dict the xml response is parsed with the jq filter provided in the jq_filter field
> feat(http connector): Added xml support

- tests/aircall/test_aircall.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/oauth2_connector/oauth2connector.py
Aircall needs the client_id and client_secret sent in the body of fetch_tokens. With this fix, this is now the default behavior.
It is also possible to give arbitrary kwargs to OAuth2Connector:retrieve_tokens, they will be passed-through to the body of the request
> Fix/oauth2connector retrieve tokens for aircall needs the client_id and client_secret

- setup.py
Bumps connector version to 0.43.5. 
Onboards the fix on Aircall connector see [related pr](https://github.com/ToucanToco/toucan-connectors/pull/236)
> bumps connectors version to 0.43.5

- setup.py
Bumps toucan connector version to 0.43.6 to add a fix on Aircall connector.
The fix allow to write the correct auth_flow_id in mongo while saving the params of the oAuth2 flow
> bumps connectors version to 0.43.6

- setup.py
Bumps connector version to 0.43.7 to onboard the fix of odbc driver install script.
> bumps connectors version to 0.43.7

- setup.py
Tests on wootric are failling because of change in aiohttp version. 
I uploaded setup.py, it now requires an aiohttp version < 3.7.0 (the version introducing breaking changes)
> updated version of aiohttp in setup.py

- toucan_connectors/install_scripts/odbc.sh
The odbc.sh script now writes the drivers's configuration into: 
/usr/local/etc/odbcinst.ini file
> fix(odbc): fixed the odbc install script

- tests/test_connector.py
- toucan_connectors/micro_strategy/micro_strategy_connector.py
updated test and microstrategy connector to reflect changes from pydantic
Connectors tests were failling because of new pydantic version. 
I updated: 
- test/test_connector.py
- micro_strategy/micro_strategy_connector.py 
to reflect theses changes
> Update connectors with new pydantic version

- toucan_connectors/oauth2_connector/oauth2connector.py
the redirect_uri field has been tagged as 'not user provided'. This means that even the admin SHOULD NOT fill this field. It should be field automatically by a backend.
> fix(oauth2): Added metadata to the OAuth2ConnectorConfig. 

- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/aircall/doc.md
- toucan_connectors/google_sheets_2/doc.md
A small doc is needed to configure oAuth connectors (Gsheets & Aircall at the moment) in the secrets config window. 
The two docs were written in their respective connectors directory.
> docs: added help message to oauth connectors config

- toucan_connectors/micro_strategy/micro_strategy_connector.py
An error was raised during MicroStrategy instanciation because of pydantic receiving None default value in the password field. 
Default value was changed to ''.
> fix:MicroStrategy connector accepts empty password

- setup.py
Bump of connectors version to 0.43.14 to onboard fix on microstrategy
> chore:bump connectors version to 0.43.14

- toucan_connectors/__init__.py
Google Sheets Connectors listing in "add connectors" view was cleaned up. 
The new google sheets connector using oAuth was renamed to Google Sheets to reflect this change.
> refactor:updated gsheet connectors names

- setup.py
Onboards the changes in Google Sheets labels
> chore:bump connectors version to 43.15

- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
Changed retry limits (4 retries) and waiting time (1 second) as well as the max pages number to retrieve.
> fix: increased retry limits and decreased sleeping time

- setup.py
Bump connectors version 0.44.1 for Organization dropdown in Github Connector
> chore(version):Bump connector version to 0.44.1

- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
Page Limit (number of additional pages to retrieve when querying the API) in Github's connector was hardcoded.
To provide more flexibility, it's now added to the Data source's configuration and configurable in the Data Source's form.
> feat(Github Connector): added page_limit in data source's form

- setup.py
Bump connectors version to 0.44.3 to onboard latest version of github_connector
> chore(version): bump connectors 0.44.3

- tests/aircall/test_aircall.py
- tests/github/test_github.py
- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/github/github_connector.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
During preview of a datasource, get_slice method is called to return only a slice of the data. 
For Aircall, Google sheets & Github datasources, it now limits query & return a slice of the data.
> feat: implementation of get_slice for Aircall, Github, Googesheets

- setup.py
To onboard get_slice methods implementation in gsheets, aircall & github
> chore(versions): bump connectors v0.44.4

- tests/google_sheets_2/test_google_sheets_2.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
During preview, of gsheets_2 data source the query was made on the whole dataset and then only a subset was dispalyed.
I changed this behaviour by querying only 50 rows max in get_slice method.
> fix(Gsheets_2): get_slice now query only rows_limit rows during preview

- setup.py
Bumps connectors to 0.44.6 to onboard a fix on gsheets2 connector
> chore(versions): bump connectors v0.44.6

- setup.py
Bumps connectors version to 0.44.7 to onboard small fixes on Gitihub Connector
> chore(versions): bump connectors v0.44.7

- toucan_connectors/micro_strategy/micro_strategy_connector.py
https://trello.com/c/YE2ro8O6/4491-as-a-conceptor-when-creating-a-new-ms-connector-with-the-demo-without-pswd-i-want-the-pswd-to-be-in-the-etl
> fix(MicroStrategy Connector): Set default password if not set

- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/odbc/odbc_connector.py
Fixed convert_to_qmark_paramstyle function to handle parameters provided as list (e.g; 'quantities':[150, 154])
> fix: convert_to_qmark_paramstyle now handles list parameter

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Adding the match regex to the existing `$match` of the query does not work if the `$match` comes before other stages that affect the field we are filtering on. 
*Example*
We rename the column of the queried field of our dataset. Applying the match with the new field name before renaming the column would result in an empty dataframe, since it will try to find the new field name in the old dataset (before renaming the column) . 
We now append the match regex at the end of the query pipeline, that way we are sure any dependent pipeline step will be executed "before" the match regex.
> fix(mongo): apply match regex at the end of the pipeline

- setup.py
- toucan_connectors/__init__.py
Just forgot to add the Salesforce connector in __init__.py
> fix: Salesforce connector is now in init file

- setup.py
- tests/mssql/test_mssql.py
- tests/postgres/test_postgres.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
In the same vein as https://github.com/ToucanToco/toucan-connectors/pull/297, array interpolation was not working for mssql & postgresql. 
I've updated these connectors to allow the interpolation
> feat: enable array parameter interpolation in mssql & postgres

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR adds a default warehouse field in the Snowflake connector.
The default warehouse will used in any datasource that does not have its warehouse field defined.
None.
> snowflake: Add a default warehouse field

- tests/test_common.py
- toucan_connectors/common.py
**Before**
```python
nosql_apply_parameters_to_query(
{'foo': '{{ bar }}'},
{'bar': datetime(2020, 12, 31)}
)
```
would return
```python
{'foo': '2020-12-31 00:00:00'}
```
(there was a forced cast to string, making it impossible to keep the date type)
**After**
it returns
```python
{'foo': datetime.datetime(2020, 12, 31, 0, 0)}
```
(you can use `bar | string` or `bar.isoformat()` or `bar.strftime(args)` to get a string output)
> feat: handle datetime in nosql_apply_parameters_to_query

- tests/github/conftest.py
- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
For the Github's Business in a Box, we need to be able to stop traversing pagination when the connector detects a pull request we retrieved previously. 
This logic won't be used in current Business in a Box but in the next Architecture with the scheduled extraction script.
The idea will be: in the scheduled Github extraction script, we will retrieve the latest extracted PR from the client's bucket and give it to an instanciated Github Connector, this way it will only extract the required pages & PR.
> feat(Github Connector): enable incremental capability

- tests/http_api/test_http_api.py
- tests/test_auth.py
- toucan_connectors/auth.py
- toucan_connectors/http_api/http_api_connector.py
* Created a new auth oauth2_oidc method in auth.py
* This method is usable in HttpApi connector and will take care of automatically retrieving an id_token with a refresh_token from a given token endpoint.
> feat: Automatic refresh token in HttpApiConnector

- setup.py
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/__init__.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR adds a way to handle a connection through OAuth for Snowflake.
The Snowflake model was changed to handle multiple ways of authentication (plain text and oauth for now), the OAuth authentication is already handled by the Snowflake python client, this PR only adds a way for the user to supply a OAuth token at the creation of the connector
None
> feat(snowflake): add OAuth connection support

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
avoid error `$regexMatch needs 'input' to be of type string`
> fix: support regex with non-string values

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR fixes a faulty behavior when a user tries to create a Snowflake Datasource.
When no authentication method was provided at the creation of a snowflake connector, the datasource creation would fail because the `authentication_method` field was mandatory.
This would also make `get_connection_params` fail since `authentication_method`'s value was set to `None`; thus making the method return an empty password to the snowflake python client.
This PR adds a way to default to plain text user/password authentication if no method was specified during the connector creation.
None
>  fix: behavior for default authentication for snowflake connector

- tests/aircall/test_async_funcs.py
- toucan_connectors/aircall/aircall_connector.py
Fixed wrong query_params forwarding to `_retrieve_data`
> fix:aircall query params

- setup.py
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR discards the usage of `nosql_apply_parameters_to_query` in the snowflake connector in order to use snowflake's own way of applying parameters to a query.
This PR also pins the version of `pyarrow` since the snowflake python client is not compatible (for now) with any version of pyarrow >= 0.18.
None
> fix(snowflake): Apply query parameters through snowflake's client

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
Previous commits introduced multiple functions that use snowflake connections to retrieve data such as the list of databases, the list of warehouses, etc.
However these functions never closed properly the connection that they used, thus leaving unnecessary and unused connections in memory.
This PR fixes that.
This PR also introduces a small change that will identify every request made through the snowflake connector as a request done by Toucan Toco for metrics on snowflake's side.
None
> fix(snowflake): Close connections after usage and mini fix

- setup.py
- tests/github/conftest.py
- tests/github/test_helpers_github.py
- toucan_connectors/github/helpers.py
Enhanced Data modelling in GithubConnector:
- CLOSED PR are now filtered out to avoid bias in Merging Time statistics
- PR Author is now the latest PR committer instead of the first
> fix(GithubConnector): Filtering CLOSED PR and changing PR author definition

- setup.py
- tests/github/conftest.py
- tests/github/test_github.py
- toucan_connectors/github/github_connector.py
For Github's Business in a Box, we need to add a date limit on PR Extraction. For now this limit is hardcoded (== 1 year). 
In a future version, it will be given as a parameter. 
Modification was done in get_pages, if dataset is Pull Requests, then stop extraction if PR creation date is older than one year. 
With the query we are using, retrieved PR are sorted by creation date Descending.
> refactor: limit PR extraction to 1 year in get_pages

- tests/aircall/test_async_funcs.py
- tests/github/conftest.py
- tests/github/test_github.py
- tests/github/test_helpers_github.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/aircall/helpers.py
- toucan_connectors/github/github_connector.py
- toucan_connectors/github/helpers.py
This PR aims to add ratelimit handling feature to Github & Aircall Connectors. 
The goal is to be able to know when the extraction reached the API Rate Limit and pause until the limit is reset. 
For Github see: https://docs.github.com/en/graphql/overview/resource-limitations
For Aircall See: https://developer.aircall.io/api-references/#rate-limiting
> feat(githubconnector, aircallconnector): added ratelimit info extraction & handling

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR adds a refresh mechanism for snowflake connectors that use an OIDC authentication mechanism.
> feat(snowflake): Add OAuth refresh mechanism

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
The regex match was case sensitive (making the lazy requester not work properly).
> fix(mongo-connector): make regex match case insensitive

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This commit fixes a previous behavior by reading the expiration timestamp from the decoded access_token instead of reading the
access_token from the oauth_args.
> fix(snowflake): Use the expiration timestamp from the oauth token provided by the IDP

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR adds the support of user defined [snowflake User Roles](https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles).
> feat(snowflake): add role specification for snowflake connector

- doc/connectors/snowflake.md
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
This PR fixes two things : 
- The previous code used the original access_token even if a refresh occured
- The user used in case of a oauth authentication was not the one provided by the external IdP but the one that was saved in the connector at its creation; this PR makes the `sub` content supersede the `user` field if providen by the IdP. This PR also makes the `user` field optional since users can be provided through a IdP connection.
> fix(snowflake): fix refresh mechanism and fix user management

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
The parameters value passed from the backend can be incompatible
with pyformat mapping (dict or array values).
I use convert to qmark method that is already used on other connectors
Another way would be to flatten parameters, but it could still leave
some incompatible values (arrays of dict).
> fix(snowflake): convert parameters to qmark style

- setup.py
This commit pins the Snowflake python connector to 2.4.1 and removes the previous pin on pyarrow.
> fix: pin python snowflake connector version

- doc/connectors/facebook_ads.md
- tests/facebook_ads/test_facebook_ads.py
- toucan_connectors/facebook_ads/enums.py
- toucan_connectors/facebook_ads/facebook_ads_connector.py
This PR adds the support of the Insights endpoint for the Facebook Ads connector
> feat(facebook ads): Add insights endpoint

- setup.py
Bump the connectors to the v0.51.5, this version adds:
- Facebook Ads: the access to the `insights` endpoint
> chore(version): bump-v0.51.5

- tests/postgres/test_postgres.py
- tests/test_common.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/clickhouse/clickhouse_connector.py
- toucan_connectors/common.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/odbc/odbc_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/sap_hana/sap_hana_connector.py
SQL connectors (mysql, postgres, mssql, etc.) don't handle jinja templating (to avoid sql injections). They only handle printf-style templating (i.e `%(var)s`).
This PR aims to provide basic functionality of jinja templating for these connectors, by turning `{{ foo }}` into `%(foo)s`.
:warning: this is limited to jinja syntax (mustaches) arount a single valid python identifier. It does not work for `{{ foo.bar }}` for example.
> feat(sql connectors): convert basic jinja to printf templating style

- setup.py
- tests/test_common.py
- toucan_connectors/common.py
In some cases, we used to lose the `str` type when using the util nosql_apply_parameters_to_query, leading to errors.
> fix(nosql apply parameters to query): keep str type when appropriate

- tests/azure_mssql/test_azure_mssql.py
- tests/google_cloud_mysql/test_google_cloud_mysql.py
- tests/mysql/test_mysql.py
- tests/oracle_sql/test_oracle_sql.py
- tests/postgres/test_postgres.py
- tests/sap_hana/test_sap_hana.py
- tests/test_common.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/clickhouse/clickhouse_connector.py
- toucan_connectors/common.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/mssql/mssql_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/odbc/odbc_connector.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/sap_hana/sap_hana_connector.py
Centralize sql query manipulations in a dedicated util, so it's easier to add or modify common behaviours.
> refactor(sql connectors): add util pandas_read_sql

- tests/google_sheets_2/test_google_sheets_2.py
- tests/http_api/test_http_api.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
GoogleSheets2DataSource now contains a parse_dates field that contains the name of column which content will be treated as datetime
:x:
> feat(google sheets2): the GoogleSheets2 can now parse dates

- setup.py
- tests/snowflake/test_snowflake.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/snowflake/snowflake_connector.py
- fix(snowflake): conversion to printf templating style was forgotten in snowflake connector
- fix: bad regex was used in convert_to_qmark_paramstyle
- chore: bump version to 0.51.11
> fix(snowflake): fix snowflake parametrization

- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/toucan_connector.py
This PR adds three fields to the Snowflake connector :
* _sso_credentials_access
* sso_credentials_keeper
* user_tokens_keeper
These fields will be used in laputa to inject at runtime tokens and credentials keeper to allow the connector to use these credentials in a secure way instead of relying on plain text data.
This fields will also allow the connector to update these credentials if needed.
> feat(SSO): Make snowflake connector be able to hold external tokens and credentials

- toucan_connectors/github/github_connector.py
- toucan_connectors/toucan_connector.py
Add the forgotten "_oauth_trigger" attribute in Github Connector. 
& Remove deprecated `is_oauth2_connector` function from coverage.
> fix: add github connector _oauth_trigger attribute

- setup.py
chores(versions): bump connectors version 0.52.1
* Re-add (deprecated) is_oauth2_connector function
* Add GithubConnector missing attribute `_oauth_trigger`
> chores(versions): bump connectors version 0.52.1

- setup.py
- tests/snowflake_oauth2/conftest.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
* Adapt the Snowflake Oauth2 connector following changes in oauth2 flow management in backend 
* Hide non-user defined fields/
> fix(snowflake oauth): hide non user defined fields

- setup.py
- tests/snowflake/test_snowflake.py
- toucan_connectors/snowflake/snowflake_connector.py
Change the definition of the snowflake connector : remove fields `oauth_token` and `oauth_args` (this data is now automatically forwarded from laputa through the fields `sso_credentials_keeper` and `user_tokens_keeper`), and add new fields `token_endpoint` and `token_endpoint_content_type` (which were previously in `oauth_args`).
:question: maybe we could forward the `token_endpoint` information from laputa, too.
:warning: this is a breaking change and will require a migration of etl_configs
> feat(snowflake): use new tokens and secrets forwarded from caller

- tests/azure_mssql/test_azure_mssql.py
- tests/google_cloud_mysql/test_google_cloud_mysql.py
- tests/mssql/test_mssql.py
- tests/mssql_TLSv1_0/test_mssql_TLSv1_0.py
- tests/odbc/test_odbc.py
- tests/revinate/test_revinate.py
- tests/sap_hana/test_sap_hana.py
- toucan_connectors/azure_mssql/azure_mssql_connector.py
- toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
- toucan_connectors/revinate/revinate_connector.py
- toucan_connectors/sap_hana/sap_hana_connector.py
Some connectors weren't properly working as any SecretStr (e.g. password) was marked as required. 
In the backend, for some routes, we need a dummy value for the SecretStr (to retrieve the configured connectors for example).
Hence, SecretStr doesn't need to be marked as required.
https://trello.com/c/mJiW1k19/4803-1-as-a-c-i-would-like-to-be-able-my-connector-datasource-without-a-wrong-validation-error
> fix: set default values for secret str

- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
When mysql returns 0000-00-00, it is left as a string in the pandas dataframe, leading to mixed dtype.
With this fix, this value is replaced by NaT, so we have a clean dataframe.
> fix: handle datetime 0000-00-00 in mysql connector

- setup.py
- tests/docker-compose.yml
- tests/sap_hana/test_sap_hana.py
- toucan_connectors/sap_hana/sap_hana_connector.py
cf. https://github.com/ToucanToco/toucan-connectors/issues/440
> fix(hana) rollback upgrade

- setup.py
- tests/test_connection_manager.py
- tests/test_query_manager.py
- tests/test_snowflake_common.py
- toucan_connectors/connection_manager.py
- toucan_connectors/query_manager.py
- toucan_connectors/snowflake_common.py
PR for information
This PR is on feat/query_pool_v2 but need to change for master
ConnectionManager class needs to be simplfied 
- _get_wait method is useless to retrieve connection, between gunicorn system and urllib in snowflake library, it is impossible to have multiple thread who needs a connection at the same time 
For more information about snowflake library: https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/network.py#L1059
For more information about urllib: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#customizing-pool-behavior
> Feat(snowflake): simplify connection_manager

- tests/http_api/test_http_api.py
- tests/test_connector.py
- toucan_connectors/toucan_connector.py
Add a `get_cache_key` method, which will return a key used for caching (see PAT 231).
The key should be the same if the query is the same.
> feat: add get_cache_key method for queries caching

- setup.py
- tests/http_api/test_http_api.py
- tests/mongo/test_mongo.py
- tests/test_connector.py
- tests/test_datasource.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/toucan_connector.py
Add a field `cache_ttl` (optional int, defaults to None) to models `ToucanConnector` and `ToucanDataSource`.
These fields will be used by the caching system implemented in laputa.
The ttl of the datasource will take precedence over the one of the connector.
---
This PR also contains a fix for `get_cache_key` (now it works for mongo).
> feat: add `cache_ttl` field on ToucanConnector and ToucanDataSource

- README.md
While setting up my environment using `pip install -e [all]` i got an error with the package `pyodbc` while compiling it !
Am on Ubuntu 20, and i discovered i needed a binding to be installed first before i can install that package !
To solve that i just ran this :
```bash
sudo apt-get update
sudo apt-get install unixodbc-dev
```
And that's what i just added in the [README.md](https://github.com/ToucanToco/toucan-connectors/blob/fix/pyodbc-readme-install/README.md) file !
N/A
> fix: add odbc installation in the readme(for linux systems)

- tests/http_api/test_http_api.py
- tests/snowflake/test_snowflake.py
- tests/test_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Use new method to get_identifier (method defined for cache)
- Implement a new method to get_identifier from Connector information
- Implement specific method for SnowflakeoAuth2Connector (impossible to serialize object from OAuth2Connector)
> feat(get_identifier): use method to get an unique identifier

- tests/aircall/test_aircall.py
- tests/facebook_ads/test_facebook_ads.py
- tests/github/test_github.py
- tests/google_adwords/test_google_adwords.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/hubspot/test_hubspot.py
- tests/linkedinads/test_linkedinads.py
- tests/one_drive/test_one_drive.py
- tests/salesforce/test_salesforce.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- toucan_connectors/aircall/aircall_connector.py
- toucan_connectors/facebook_ads/facebook_ads_connector.py
- toucan_connectors/github/github_connector.py
- toucan_connectors/google_adwords/google_adwords_connector.py
- toucan_connectors/google_sheets_2/google_sheets_2_connector.py
- toucan_connectors/hubspot/hubspot_connector.py
- toucan_connectors/linkedinads/linkedinads_connector.py
- toucan_connectors/one_drive/one_drive_connector.py
- toucan_connectors/salesforce/salesforce_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
refactor(oauth2 connectors): the _oauth2_connector property of oauth2 connectors is no longer set using __dict__. It is now properly declared as private variables for pydantic. This excludes them from the json generated by `.json()`
> refactor(oauth2 connectors): the _oauth2_connector property of oauth2 connectors is no longer set using __dict__

- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
Get rid of the error when both table and query are set. Query should have priority.
This is the same behavior as postgres and mssql connectors.
> fix(mysql): support table and query

- setup.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
Fix this issue: 
`--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
msg = self.format(record)
File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
return fmt.format(record)
File "/home/raphael/PycharmProjects/laputa/laputa/common/log.py", line 188, in format
return json_serializer.dumps(log_object).decode('utf-8')
File "/home/raphael/PycharmProjects/laputa/laputa/common/utils/json_serializer.py", line 59, in dumps
return orjson.dumps(
TypeError: Type is not JSON serializable: ResultMetadata
`
> fix(snowflake common): fix describe result logging

- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
Snowflake doesn't accept multiple queries in a single execution.
To use specific database and a specific warehouse, we made : 
- 'USE WAREHOUSE my_warehouse; USE DATABASE my_datebase'
The new format is : 
- 'USE WAREHOUSE my_warehouse'
- 'USE DATABASE my_database'
https://trello.com/c/gPj8WUrq/1238-snowflake-connector-fix-query-fail-because-of-multiple-statement-query
> fix(multiple_queries): remove multiple queries one execute

- tests/snowflake/test_snowflake.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- tests/test_snowflake_common.py
- toucan_connectors/snowflake_common.py
For Snowflake connection only
In some cases we want to store the query as an object (table, schema, columns) instead of a string.
Adding this as a hidden field so we can store the query object in db
> feat(snowflake): add hidden field to store query as object

- tests/test_common.py
- toucan_connectors/common.py
…
let's say that we have the following query:
`SELECT foo FROM bar WHERE x = %(VARIABLE)`. 
It must be translated to `SELECT foo FROM bar WHERE x = ?` 
The issue is that our templates are string. 
So we could get the query `SELECT foo FROM bar WHERE x = '%(VARIABLE)'` when using the weaverbird SQL generator, wich would be translated to  `SELECT foo FROM bar WHERE x = '?'` leading to literal ? in the results
> feat(parameters): now handle the case where some parameters in a datasource are quoted, especially for SQL.

- setup.py
- tests/google_sheets/test_google_sheets.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/test_connector.py
- toucan_connectors/toucan_connector.py
This PR fixes an issue encountered in data prep: 
our open source data prep pipeline ("youPrep") for mongo doesn't allow manipulating columns named with numbers.
To ensure we have the same behaviour with "youPrep" for pandas we force all column names to strings.
> fix(df columns type): force returned df columns to str

- tests/clickhouse/test_clickhouse.py
The latest ClickHouse release https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#new-feature adds an `INFORMATION_SCHEMA` database and we see this in an assertion in our tests, this PR updates the test so that it does not fail.
> fix(clickhouse): add information_schema db to tests

- tests/test_auth.py
- toucan_connectors/auth.py
RFC 2617 standard on HTTP Authentication states that credentials should consist of at least a scheme and arbitrary parameters:
`credentials = auth-scheme #auth-param`
In practice auth-scheme is often "Bearer" because it is used in the OAuth2 standard [1, 2]. This is our default, the initial request made to the `custom_token_server` will be used in the the Authorization header after the Bearer auth-scheme.
This PR adds support for alternative auth-schemes in this case the `filter` should emit the compltete value of the Authorization header. For example : 
```json
{"token": "<some token>"}
```
```cson
filter : '"AnaplanAuthToken \(.token)"'
```
will result in a header that looks like this : 
```
Authorization: AnaplanAuthToken <some token>
```
This change is backward compatible (keep the …
> feat(http): support for custom auth-schemes when using custom_token_server

- setup.py
Upgrade `aoihttp` following this alert : https://github.com/ToucanToco/toucan-connectors/security/dependabot/setup.py/aiohttp/open
It was pinned by Florent here : https://github.com/ToucanToco/toucan-connectors/commit/bf8e03061f5fd811fa70e3c8cc70010bd774e6a4 but I don't know why.
https://github.com/ToucanToco/toucan-connectors/security/dependabot/setup.py/aiohttp/open
> fix(deps) upgrade aiohttp

- setup.py
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
The mongo connector was not filling metadatas properly.
`total_returned_rows` was the size of the collection.
`total_rows` was empty
Now, `total_rows` is the len of the collection
`total_returned_rows` is not modified by this PR, but should be deprecated at some point
> fix(mongo connector): mongo `get_slice` method now return total count in `total_rows` and returned count in `total_returned_rows`

- tests/one_drive/test_one_drive.py
- toucan_connectors/one_drive/one_drive_connector.py
Hi Toucan,
Here is my PR to append multiple sheets in One Drive.
The user can specify a singe sheet or a comma separeted list of sheets (ie: "sheet1, sheet2" or "sheet1,sheet2").
If multiple sheets are defiened by the user, a ` __sheetname__` column containing the sheet name will be created.
> feat(one drive): append multiple sheets

- toucan_connectors/toucan_connector.py
The `df_memory_size` field of the DataStats class is so useful to know the size of the downloaded/extracted dataframe before "pagination truncation" that we should have it set all the time !
> feat(base connector): always set df memory size TCTC-1472

- setup.py
- sonar-project.properties
- toucan_connectors/redshift/redshift_database_connector.py
Releasing the 1337 version + set autocommit to true in redshift connector. see: https://stackoverflow.com/q/22019154 
It was causing issues because, with autocommit off, failing queries blocked further valid queries.
> chore: enable autocommit & release 1.3.37 for redshift

- doc/connectors/postgres.md
- setup.py
- sonar-project.properties
- tests/postgres/test_postgres.py
- toucan_connectors/postgres/postgresql_connector.py
https://github.com/ToucanToco/toucan-connectors/pull/527 introduced a status check for postgres, that appeared alays red in cas the parameter `hostname` were used.
I actually noticed that only `host` was enough, so I suggest we only keep this one.
A migration will be needed from hostname to host for existing connections.
> fix(postgres): not using hostname any more (host is enough) TCTC-1603

- tests/redshift/test_redshift.py
- tests/test_sql_query_helper.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake_common.py
- toucan_connectors/sql_query_helper.py
Fix a feature introduced in https://github.com/ToucanToco/toucan-connectors/pull/443 that was apparently based on wrong assumption : preventing count requests when an SQL query contained an aggregation method (sum, avg, min, etc.).
The pagination is entirely based on having the total row count. So not having it completely break the end user experience in pipeline editors.
Also, it was initialized at -1 instead of None, not a "true optional" field.
Last but not least, the regex looking for aggregation methods was not accurate enough to make the difference with the "count" method and a column named "country" :sweat_smile:
> fix(sql): get row count for queries using aggregation methods TCTC-1567

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
- tests/conftest.py
Add a dev container to be used with vscode to ease the collaboration with external contributors.
Installing the repo locally can be tricky, thus the devcontainer can be use to have an independant dev environment without having to deal with dependencies issues.
> Add .devcontainer definition

- CHANGELOG.md
- setup.py
- sonar-project.properties
- Bump on toucan-connectors from 1.3.43 to 2.0.0.
- Added a changelog file for this repo.
> chore: bump from 1.3.43 to 2.0.0

- tests/google_sheets/test_google_sheets.py
- toucan_connectors/__init__.py
- toucan_connectors/google_sheets/google_sheets_connector.py
- toucan_connectors/toucan_connector.py
(in registry)
Otherwise, this parameter is never added to the registry and can't be used to init connections.
> fix(google-sheets): pass service id in connector infos

- setup.py
- sonar-project.properties
- tests/google_sheets/test_google_sheets.py
- toucan_connectors/google_sheets/google_sheets_connector.py
Reproduce some feature of GoogleSheets2 datasource form in the GoogleSheets connector: 
- order fields to display "domain", "spreadsheet_id" & "sheet" above "validation rules" & "parameters"
- provide available sheets list when "spreadsheet_id" have been filed
:no_entry_sign:
> feat(google-sheets): order fields & list available sheets in datasource form TCTC-1819

- tests/http_api/test_http_api.py
- tests/test_connector.py
- tests/test_json_wrapper.py
- toucan_connectors/json_wrapper.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/toucan_connector.py
if the connector itself is using jinja template, different datasources might have the same cache key.
To solve this issue, the connector is rendered before computing the cache key
TCTC-1882
> feat(cache key): the connector itself is rendered with `datasource.parameters` as a context (TCTC-1882)

- tests/postgres/test_postgres.py
- tests/redshift/test_redshift.py
- tests/snowflake/test_snowflake.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake_common.py
Add `language` & `query_object` attributes to snowflake, redshift & Postgres
> chore(PG, SF, RS): add language & query_object attributes [TCTC-1715]

- setup.py
- sonar-project.properties
- toucan_connectors/postgres/postgresql_connector.py
issue on postgres: only the last DB tree was returned when calling `get-model`
> fix(postgres): format all result from get model

- doc/connectors/odbcconnector.md
- tests/odbc/test_odbc.py
- toucan_connectors/odbc/odbc_connector.py
Add `autocommit` option, keep the connector default (False).
https://github.com/mkleehammer/pyodbc/wiki/Connection#autocommit
https://github.com/ToucanToco/toucan-connectors/issues/573
> (feature) odbc add autocommit option

- setup.py
- sonar-project.properties
- toucan_connectors/redshift/redshift_database_connector.py
Fix the query used in `get-model` to retrieve database model. 
It filters the `padb_harvest` database that seems to be a mere duplicate of `dev` database.
> fix(redshift): filter duplicate sys table from get-model query

- tests/snowflake/test_snowflake.py
- tests/test_connector.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Fix a issue on Google Big Queries request using the custom variable syntax `@my_var` 
by making the default cache key "dumber" to produce different cache key for queries using custom variable syntax
(other than `{{ }}` & `@()`.
Resolution path considered but not chosen includes : 
- dropping support for this custom syntax on user side -> would require checking is the query does not use this syntax & do this for every connector with specific variable syntax, nope
-  overwriting `_render_datasource` for BigQuery like it was done for Mongo, Snowflake & Http -> apparently not possible, the BigQuery client does not seem to have a method returning interpolated query.
> fix: support custom variables syntax in default cache key TCTC-1903

- setup.py
- sonar-project.properties
The upgrade of bigquery client from 2 to 3 changed the dtypes used for nullable integers.
These types, quite experimental by now according to [docs](https://pandas.pydata.org/docs/user_guide/integer_na.html), are not compatible with eval and some other operations.
While we or pandas support these types in the eval / formula step of weaverbird, I suggest pinning this dep to v2
> fix(bigquery): fix client lib to v2 TCTC-2444

- setup.py
- sonar-project.properties
- tests/databricks/test_databricks.py
- toucan_connectors/databricks/databricks_connector.py
Databricks `get_status` needs to use an autocommit connection.
> fix: databricks get status

- tests/test_common.py
- toucan_connectors/common.py
Adds an util `infer_datetime_dtype` and use it for each sql connector. Its purpose is to properly set the dtype on datetime columns.
Performance impact : 4ms on *shark attack* dataset (6750 rows, 16 columns).
> fix(sql connectors): set `datetime` dtype when needed [TCTC-1576] [TCTC-2521]

- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
This allows to pass array query parameters. These were defined as strings until now,
which caused issues when using them with BigQuery functions expecting an array, such
as UNNEST.
> feat(google BigQuery): Add support for array query parameters TCTC-1447

- toucan_connectors/google_big_query/google_big_query_connector.py
without date_as_object=False, date columns get dtype 'object' instead of 'datetime64[ns]'
> feat(googlebigquery): parse dates as datetime dtype [TCTC-2521]

- Makefile
- setup.py
- sonar-project.properties
Dependencies fix :
- Upgrade requests-oauthlib & oauthlib on a minor version to match laputa
- Bump toucan-connectors from 3.5.1 to 3.5.2
PS: Already bumped (was to sync dependencies with laputa and test laputa migration from pip to poetry support here : https://github.com/ToucanToco/laputa/pull/5135 )
> fix: dependencies (accordingly to laputa)  [TCTC-2752]

- setup.py
- sonar-project.properties
- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
Fix an issue where `resp.json()` is not working in http api connector
> fix: http api json decode error

- tests/mongo/fixtures/docs.json
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
With the `get_df_with_regex` we could only search for a string on a single field given as a param. We couldn't also get the whole slice of data. That's why we needed to create a new function that returns the slice and allows searching for a string on multiple columns given as an array of strings in the params. 
Feature needed for https://toucantoco.atlassian.net/jira/software/c/projects/TCTC/boards/13?modal=detail&selectedIssue=TCTC-2532&quickFilter=87
> feat(mongo-connector): allow search on multiple columns [TCTC-2532]

- setup.py
- sonar-project.properties
- bump awswrangler to >= 2.15 in order to support pandas >= 1.3
- pin explicitly pyarrow<7 when installing snowflake, otherwise it doesnt seem to be taken in account :shrug: despite being specified here: https://github.com/snowflakedb/snowflake-connector-python/blob/v2.7.8/pyproject.toml#L9
> chore: bump awswrangler to support pandas >=1.3

- doc/connectors/elasticsearch.md
- poetry.lock
- pyproject.toml
- tests/docker-compose.yml
- tests/elasticsearch/test_elasticsearch.py
- toucan_connectors/elasticsearch/elasticsearch_connector.py
- Unpin + bump elasticsearch from 7.17.4 to 8.2.2
- Updated the connector and tests due to the `send_get_body_as` param deprecated on 7.16 (see [HERE](https://github.com/elastic/elasticsearch-py/releases?page=3#:~:text=Deprecated%20the%20send_get_body_as%20parameter.%20This%20parameter%20is%20no%20longer%20necessary%0Aas%20APIs%20all%20use%20non%2DGET%20HTTP%20methods%20when%20using%20a%20body.))
> feat: add support for elasticsearch 8 [TCTC-1907]

- CHANGELOG.md
- pyproject.toml
Bump connectors from 3.10 to 3.11
Changes related to https://github.com/ToucanToco/toucan-connectors/pull/609
> chore: bump from 3.10 to 3.11

- CHANGELOG.md
- pyproject.toml
Bump toucan-connectors from 3.12.0 to 3.13.0
See (https://github.com/ToucanToco/toucan-connectors/pull/616) for more details !
> chore: bump toucan-connectors from 3.12.0 to 3.13.0

- toucan_connectors/google_big_query/google_big_query_connector.py
As the frontend sends the 'Database' attribute for graphical interface we need to ignore it when validating the model.
> fix(bigquery): ignore database extra attribute

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Toucan connectors now support by-column regex filtering
https://toucantoco.atlassian.net/browse/TCTC-3332
https://github.com/ToucanToco/laputa/pull/5280
> feat: multi-column filtering [TCTC-3332]

- tests/utils/test_datetime.py
- toucan_connectors/toucan_connector.py
- toucan_connectors/utils/datetime.py
BigQuery and Athena translators store objects in the SQL DATE type as datetime.date objects.
That is correct, but pandas does not consider datetime.date objects as datetimes. As a result, when
serializing and deserializing a dataframe containing datetime.date objects, these get dumped/loaded
as strings.
This change ensures the right type is used.
TCTC-3424
* [x ] Unit tests for the changes exist
* [ x] Tests pass on CI and coverage remains at 100%
* [ x] Documentation reflects the changes where applicable
> fix: Ensure STL dates are returned with the right dtype TCTC-3424

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/awsathena/awsathena_connector.py
- toucan_connectors/mysql/mysql_connector.py
Old Athena & Mysql datasources config might have a Table attribute. 
We add them back but hidden from the UI to avoid breaking old configs.
> fix(mysql,athena) hidden table attr

- pyproject.toml
- sonar-project.properties
- tests/mongo/fixtures/docs.json
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
https://toucantoco.atlassian.net/browse/TCTC-3545
Searching for
```yml
or:
- foo: Foo
bar: Bar
- baz: Baz
qux: Qux
```
resulted in (pseudo mongo)
```yml
$or:
- foo: matches Foo
- bar: matches Bar
- baz: matches Baz
- qux: matches Qux
```
but it should result in (pseudo mongo)
```yml
$or:
- $and:
- foo: matches Foo
- bar: matches Bar
- $and:
- baz: matches Baz
- qux: matches Qux
```
It's more reasonable when reading the bug ticket: basically if I want to filter rows where name is John or Johnny and age is 20 I don't wanna be showned a John that is not 20 years old
> fix(mongo-connector): search [TCTC-3545]

- CHANGELOG.md
- doc/connectors.md
- doc/connectors/awsathena.md
- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
Allow to toggle Create Table As (CTAS) in athena connector. For small result sets, disabling it is faster because it reduces latency
> feat(athena): Add an option allowing to toggle CTAS

- CHANGELOG.md
- pyproject.toml
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
Both queries (SHOW DATABASES and the more complex one in build_database_model_extraction_query),
do not require a database to function.
Currently, the database was forced to "mysql", which caused the connection to fail in case the database
did not exist or if the SQL user used by the connector did not have sufficient permissions.
> fix(mysql): Do not specify the database for schema-related functions TCTC-3768

- tests/mysql/test_mysql.py
- tests/test_connector.py
- toucan_connectors/awsathena/awsathena_connector.py
- toucan_connectors/google_big_query/google_big_query_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Always provide a db_name in mysql's `get_model` because depending on the SQL user's rights, now having a db can cause
SQL errors.
TCTC-3768
> fix(mysql): Always specify db_name in get_model TCTC-3769

- tests/redshift/test_redshift.py
- toucan_connectors/redshift/redshift_database_connector.py
Add an option to disable TCP keep-alive in the redshift cnnectro
relates to TCTC-3769
> feat(redshift): Add an option to toggle TCP keep-alive (enabled by default) TCTC-3769

- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
We were previously using json_arrayagg, which was introduced in MySQL 5.7.22. In order to be compatible with older MySQL
versions, do the column information aggregation on the client side.
relates to TCTC-3768
> fix(mysql): Do not use too modern aggregation functions when retrieving project structure TCTC-3768

- CHANGELOG.md
- pyproject.toml
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
- feat: removed te column from mongo translator
- test: add tests related to that change
- chore: bump toucan-connectors from 3.20.1 to 3.20.2
> feat: remove "_id" column from DataFrame on mongo_connector [TC-3788]

- poetry.lock
- pyproject.toml
This allows us to upgrade pyarrow to 8.0.0 -> #690
> chore: bump snowflake-connector-python to 2.7.12

- tests/google_sheets/test_google_sheets.py
- tests/google_sheets_2/test_google_sheets_2.py
- tests/one_drive/test_one_drive.py
- tests/utils/test_datetime.py
- toucan_connectors/utils/datetime.py
pd.to_datetime() creates np.datetime64 objects, which are naive. Thus, in order to be converted to UTC, we must pass utc=True.
relates to TCTC-4151
> fix(utils): Pass utc=True in sanitize_df_dates util

- tests/mongo/test_mongo.py
- tests/mysql/test_mysql.py
- tests/postgres/test_postgres.py
- tests/test_connector.py
- toucan_connectors/mongo/mongo_connector.py
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/postgres/postgresql_connector.py
- toucan_connectors/toucan_connector.py
We want to get the target source version for each engine, but on this Pull Request, we will be focusing on Mysql/PostgreSql and mongo.
- add an abstract method in a class called VersionableEngineConnector from toucan_connector
- set up target version handler for mysql + test
- set up target version handler for postgresql + test
- set up target version handler for mongo + test
> feat: get target version per engine [TCTC-3498]

- CHANGELOG.md
- doc/connectors/mysql.md
- pyproject.toml
- sonar-project.properties
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
Adds support for REQUIRED ssl mode in MySQL connector
> feat(mysql): Add support for REQUIRED ssl_mode TCTC-4228

- CHANGELOG.md
- tests/postgres/test_postgres.py
- toucan_connectors/postgres/postgresql_connector.py
* fix(postgresql): Ensure we always use default_database if provided
closes TCTC-4462
> fix(postgresql): Ensure we always use default_database if provided TCTC-4462 (#740) [backport]

- CHANGELOG.md
- toucan_connectors/google_sheets/google_sheets_connector.py
Updated the `dateTimeRenderOption` parameter from *SERIAL_NUMBER* to *FORMATTED_STRING* to load dates as simple string, see : https://developers.google.com/sheets/api/reference/rest/v4/DateTimeRenderOption
*EDIT1*: Added a new param to let the user trigger that option as default, see : https://github.com/ToucanToco/toucan-connectors/pull/800#issuecomment-1334930144 and https://github.com/ToucanToco/toucan-connectors/pull/800#issuecomment-1334971509
PS: to be honest... am wondering if we really have to do this change since the date infering will be "broken"... seems to be a product question tho... ?
If the fix seems to be okay, it should be cherry-pick on V3 too.
> fix: google-sheet dates load double to string [TCTC-4148]

- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
When there is a void match of a column inside an "and" condition, it is not filtered from the query, resulting to empty results of data. 
x
> fix(filters): handle __VOID__ in $and match conditions

- CHANGELOG.md
- tests/mysql/test_mysql.py
- toucan_connectors/mysql/mysql_connector.py
we want to have ssl_ca, ssl_cert and ssl_key as optional params for an ssl connexion
> feat: allow empty field mysql ssl [TCTC-5306]

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
This is just a bump from 4.5.1 to 4.6.0 for toucan-connectors.
> chore: release toucan-connectors from 4.5.1 to 4.6.0

- tests/http_api/test_http_api.py
- tests/one_drive/test_one_drive.py
fix the CI by mocking http calls to jsonplaceholder free API.
looks like github action ip addresses are blacklisted.
> fix: http tests failed on CI

- tests/http_api/test_http_api.py
- tests/one_drive/test_one_drive.py
This is just a backport of : #1151
fix: http tests failed on CI
> fix: http tests failed on CI (#1151)

- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
In case of a big project structure, we were struggling to fetch datasets using the
`_get_project_structure_fast` method in some huge cases, even tho it was implemented
too to speed up that process.
So, to solve that problem of latency, We tested numerous solutions such as *paginator_iter* from gbq lib,
update the fetching page per page and finaly, this is how we optimized it in 2 steps :
- For the method `_get_project_structure_fast`, if the project structure is expected to be large, we might want to paginate the results instead of returning a single DataFrame to avoid memory issues. that's why we added a query_job with the new parameter in the config : `_PAGE_SIZE`, this will help us paginate results regarding that parameter and `_MAXIMUM_RESULTS_FETCHED`, to impose ourself a limit of …
> feat: google big query database selection much faster [TCTC-6113]

- CHANGELOG.md
- pyproject.toml
> chore: bump connectors from 4.6.0 to 4.7.0

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tests/conftest.py
To fix (when poetry install):
```
File "/tmp/tmpz5of1_if/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
raise AttributeError(attr)
AttributeError: cython_sources
at env/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
143│
144│                 error = ChefBuildError("\n\n".join(message_parts))
145│
146│             if error is not None:
→ 147│                 raise error from None
148│
149│             return path
150│
151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (5.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml …
```
> fix: pyyaml on weel PEP 541

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
This brings https://github.com/ToucanToco/toucan-connectors/pull/1228
> chore: bump toucan-connectors from 4.7.2 to 4.7.3

- CHANGELOG.md
- toucan_connectors/install_scripts/mssql.sh
- toucan_connectors/install_scripts/mssql_TLSv1_0.sh
By using default repo (debian/12) we encountered this error: https://learn.microsoft.com/en-us/answers/questions/1328834/debian-12-public-key-is-not-available
Solution is to force the usage of debian/11 (this is what is done in the "build-image" stage of laputa's Dockerfile)
> fix: lts mssql install script [TCTC-6583]

- CHANGELOG.md
- doc/connectors/google_big_query.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
- toucan_connectors/google_credentials.py
- Explicit Exception information when data are not available when an ValueError ( on empty data in the dataframe when concatenate)
- Fix a ValidationError introduced in the previous bump (All GoogleCredentials should no be "mandatory"/"required" for the GoogleBigQuery connector)
- Add a fallback on GoogleCredentials login, so that if the jwt-token is not valid anymore, we can still connect with GoogleCreds if they are available
> fix(gbq): Validation error on mandatory GoogleCreds missing + add descriptive Exception message on missing datas [TCTC-6756]

- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
get the "good" and "valid" project-id from the connector configuration
When both JWT and GoogleCreds were sets, on the "configuration for listing tables and schemas", we were using the wrong project-id to make requests, now, we make sure the jwt-credentials is checkec but also contains all informations needed.
- fix: fallback when the project-id is not well get from either the jwt_credentials or the google-credentials
- add some Unit tests to illustrate that 
- doc: update the CHANGELOG.md
this branch is deployed on the ange guru and can be tested on the app TCTC-6942
> fix: get good project_id from jwt or google-creds when they are set or not [TCTC-6942]

- CHANGELOG.md
- toucan_connectors/install_scripts/mssql.sh
- toucan_connectors/install_scripts/mssql_TLSv1_0.sh
Same fix than https://github.com/ToucanToco/toucan-connectors/pull/1246, but for `master`
> fix: fix mssql install scripts by forcing debian/11 deb repo

- toucan_connectors/databricks/databricks_connector.py
- toucan_connectors/install_scripts/databricks.sh
I included a very small update of the connector, to be able to change the UID field of the connection string.
> fix(databricks): update databricks ODBC connector

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- sonar-project.properties
Because we can't deploy on pypi a package that has a direct git dependency
> chore: v3.23.21

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/install_scripts/oracle.sh
Fix oracle install script by replacing gdown.pl with wget and fixing the archive hosted on our cloud
> fix(lts): oracle install script

- CHANGELOG.md
- tests/elasticsearch/test_elasticsearch.py
- toucan_connectors/elasticsearch/elasticsearch_connector.py
Disable the internal verification of the elasticsearch client that checks if the root `/` of the provided URL returns a a compatible payload.
This internal verification, for some reason, does not use the basic auth provided by http_auth. So this check fails when the client configuration ask for authentication for the `/` route.
https://github.com/elastic/elasticsearch-py/blob/v7.17.6/elasticsearch/transport.py#L532
https://github.com/elastic/elasticsearch-py/blob/v7.17.6/elasticsearch/transport.py#L216
https://toucantoco.slack.com/archives/C823R095H/p1705597838374409
> fix(elasticsearch): disable verification

- CHANGELOG.md
- pyproject.toml
- tests/mongo/test_mongo.py
- toucan_connectors/mongo/mongo_connector.py
Work items:
- Added a new `max_pool_size` parameter to MongoConnector, which defaults to 1 (PyMongo's default pool size is 100).
- Ensure mongo clients are closed after usage. This may seem sub-optimal, but a typical connector usage is instanciation -> call a single method (retrieve data or get_status) -> close the client, so this seems reasonable
- Enable mypy checks on the Mongo connector, since it's by far the one we use the most
relates to TCTC-7814
> feat(mongo_connector): Make pool size configurable

- CHANGELOG.md
- tests/google_big_query/test_google_big_query.py
- toucan_connectors/google_big_query/google_big_query_connector.py
I think they were excluded by mistake in https://github.com/ToucanToco/toucan-connectors/pull/620/commits/1cc03f9e237537576afc3c7386e67c3370a9a009
> fix(gbq): do not ignore partitioning columns when listing table structure [TCTC-7946]

- .github/dependabot.yml
* Exclude `elasticsearch` from updates, as it is bound to a specific Elasticsearch version
* Do not group LTS dependency updates, as they should be done case by case (we only want security updates)
> fix(deps): tune dependabot updates 

- poetry.lock
- pyproject.toml
- toucan_connectors/toucan_connector.py
It was only used by the lightspeed connector, which has been removed in #1036
The lib has not been updated since 2019: https://pypi.org/project/bearer/, and the associated repo has been deleted. The bearer.sh service seems to have been discontinued
> chore: remove bearer dependencyu

- CHANGELOG.md
- pyproject.toml
- sonar-project.properties
- toucan_connectors/elasticsearch/elasticsearch_connector.py
> fix: elasticsearch form schema [TCTC-8032]

- CHANGELOG.md
- README.md
- tests/oracle_sql/test_oracle_sql.py
- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/oracle_sql/oracle_sql_connector.py
- OracleSQL: pass parameters as numeric to `read_sql`
> fix(oracle_sql): pass parameters to pandas read_sql as numeric parameters

- .github/workflows/ci.yml
- CHANGELOG.md
- pyproject.toml
- tests/awsathena/test_athena_integration.py
- tests/awsathena/test_awsathena.py
- toucan_connectors/awsathena/awsathena_connector.py
This fixes the parameter intepolation in the athena connector, which changed with awswrangler 3.0.0.
It also adds integration tests to the athena connector to avoid having hitting this kind of bug again
> fix(athena): correct interpolation for parameters [TCTC-9024]

- CHANGELOG.md
- tests/hubspot_private_app/test_hubspot.py
- toucan_connectors/hubspot_private_app/hubspot_connector.py
Add ability to list and select custom datasets.
I slightly refactored the api so "classic" datasets are handled the same way as custom datasets (using `client.crm.objects`).
> feat(hubspot): allow to list and select custom datasets [TCTC-9025]

- CHANGELOG.md
- toucan_connectors/toucan_connector.py
Rather than using python's `sum` built-in with `apply`, directly rely on pandas' `sum` to concatenate Series.
Results in a ~3x speed-up of the format_db_model method
> feat: improve performance of DiscoverableConnector.format_db_model

- CHANGELOG.md
- tests/test_auth.py
- toucan_connectors/auth.py
- Adds `token_header_name` option to `CustomServerToken` authentication method.
> feat: add token_header_name option to http connectors (TCTC-8945)

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- toucan_connectors/mysql/mysql_connector.py
- toucan_connectors/redshift/redshift_database_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
- toucan_connectors/toucan_connector.py
Laputa now calls get_model with some extra parameters, but these parameters were not added for 3 sql connector's `get_model` method : 
- mysql
- redshift
- snowflake oauth2
When get_model fails, the screen supposed to list db tree structure loads forever (cf. jira card https://toucantoco.atlassian.net/browse/TCTC-9223)
> fix(mysql): get_model now supports extra kwargs so it doesnt crash [TCTC-9223]

- CHANGELOG.md
- tests/test_common.py
- toucan_connectors/common.py
For example this expression  
```
{{ {}.get('LABEL', 250) }}
```
now outputs `250` instead of `"250"`
> fix: jinja templates containing parentheses or curly braces are not limited to output strings anymore

- CHANGELOG.md
- toucan_connectors/google_big_query/google_big_query_connector.py
Now it's both faster and returns more results (it used to truncate results when the db has a lot of tables / columns).
> chore: bigquery faster getmodel

- CHANGELOG.md
- toucan_connectors/toucan_connector.py
https://toucantoco.atlassian.net/browse/TCTC-7385
> feat: when testing connection, set timeout to 10s when checking if port is opened [TCTC-7385]

- CHANGELOG.md
- tests/http_api/test_http_api.py
- toucan_connectors/common.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/http_api/http_api_data_souce.py
- toucan_connectors/http_api/http_api_data_source.py
- toucan_connectors/http_api/pagination_configs.py
- toucan_connectors/snowflake/snowflake_connector.py
- toucan_connectors/toucan_connector.py
Add a `http_Pagination` attribute to `HttpAPIConnector` which works like the `auth` configuration:
- the user can activate pagination in its interface and then choose the kind of pagination he wants.
- each pagination type must have its default configuration, which will be displayed to the user once its selected
That `http_pagination` is transformed to a `PaginationConfig`. 
All PaginationConfigs works the same : 
- `apply_pagination_to_data_source` : it transform the data_source in order to add all pagination arguments needed to the API request
- `get_next_pagination_config`: it computes the next pagination_config for the next API call based on the last API response
- [optional] `get_pagination_info_filter`: it returns the JQ filter that can be used to extract pagination information from …
> feat: add pagination configs for HTTP API Connector (TCTC-9227)

- CHANGELOG.md
- tests/http_api/test_http_api.py
- toucan_connectors/http_api/http_api_connector.py
- toucan_connectors/http_api/pagination_configs.py
- toucan_connectors/utils/dataframe.py
API results where appended before any user's configured transformations (filters, flatten). We have to append resulted dataframes.
Moreover, APIs can return directly json objects, which created invalid results merging.
In addition, we have to add a data_length_filter to offset_limit pagination in case of the data result isn't relevant to compute the data length.
> fix: merge api results after their transformations (TCTC-9634)

- toucan_connectors/mongo/mongo_connector.py
Otherwise, the list has no items schema, which causes the form to be empty.
After:
> fix(mongo): correctly type the aggreation pipeline case TCTC-9713

- CHANGELOG.md
- toucan_connectors/mongo/mongo_connector.py
https://github.com/ToucanToco/toucan-connectors/pull/1813 introduced an error because each chunk has an index starting at 0 so further transformation lead to
```
ValueError: cannot reindex on an axis with duplicate labels
```
and weird behaviour like 
:upside_down_face:
> fix(mongo): igore index when concatenating chunks

- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/snowflake/snowflake_connector.py
Security issue: some users could inject malicious code in jinja templates in queries if we don't use the sandboxed environment
> fix(common): prevent injection during jinja templating (v2.23)

- tests/test_common.py
- toucan_connectors/common.py
- toucan_connectors/snowflake/snowflake_connector.py
> fix(common): prevent injection during jinja templating

- CHANGELOG.md
- tests/conftest.py
- tests/github/test_github.py
- tests/oauth2_connector/test_oauth2connector.py
- tests/one_drive/test_one_drive.py
- tests/salesforce/test_salesforce.py
- tests/snowflake_oauth2/test_snowflake_oauth2.py
- toucan_connectors/github/github_connector.py
- toucan_connectors/oauth2_connector/oauth2connector.py
- toucan_connectors/one_drive/one_drive_connector.py
- toucan_connectors/salesforce/salesforce_connector.py
- toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
We want to be able to instantiate connectors without backend fields or secrets keeper.
Oauth2 connector configs can be saved without their secrets and without the fields set by the backend for oauth2 dance.
> fix: can instantiate oauth2 connectors without oauth backend fields (TCTC-10138)

- tests/mssql/test_mssql.py
- toucan_connectors/mssql/mssql_connector.py
While the MSSQL database is booting up, the login may fail. This was introducing flakyness in the tests cases.
- discard `InterfaceError` as well as `OperationError`. If login is indeed broken (which should be rare), it will end up in a timeout error instead, which is fine.
https://github.com/ToucanToco/toucan-connectors/actions/runs/14832515032/job/41636596419
> test(mssql): discard login errors while waiting for the db to start
